Repository kyma-project/api-gateway, pull requests merged in 2022-11, with the labels that each got.

#66 Update path for api-gateway conf
  internal/helpers/config.go
Labels: lgtm, area/service-mesh, area/security, size/XS

#70 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, area/service-mesh, area/security, size/XS

#69 Update volume mount path
  config/manager/manager.yaml
Labels: lgtm, area/service-mesh, area/security, size/S

#76 Print handler for Ory Rule
  hack/oathkeeper.ory.sh_rules.yaml
Labels: lgtm, area/api-gateway, size/XS

#53 JWT Istio handler configuration
  Makefile
  README.md
  api/v1alpha1/apiRule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/apirule_types.go
  api/v1beta1/internal_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/rbac/role.yaml
  controllers/api_controller_integration_test.go
  controllers/api_controller_test.go
  controllers/apirule_controller.go
  controllers/suite_test.go
  hack/security.istio.io_authorizationpolicy.yaml
  hack/security.istio.io_requestauthentication.yaml
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/helpers/config.go
  internal/helpers/default_domain.go
  internal/processing/authorization_policy_helpers.go
  internal/processing/helpers.go
  internal/processing/processing.go
  internal/processing/processing_test.go
  internal/processing/request_authentication_helpers.go
  internal/processing/virtual_service_helpers.go
  internal/types/istio/jwt.go
  internal/types/ory/jwt.go
  internal/validation/jwt.go
  internal/validation/validate_test.go
  main.go
Labels: lgtm, area/service-mesh, size/XXL, area/security

#79 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, area/service-mesh, area/security, size/XS

#73 Add prow reporter
  controllers/suite_test.go
  internal/builders/builders_suite_test.go
  internal/processing/processing_test.go
  internal/validation/validate_test.go
Labels: lgtm, area/service-mesh, area/security, size/S

#77 Config fail early
  config/configmap/configmap.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/api_controller_integration_test.go
  controllers/api_controller_test.go
  controllers/apirule_controller.go
  controllers/suite_test.go
  internal/builders/istio.go
  internal/helpers/config.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  main.go
Labels: lgtm, area/service-mesh, area/security, size/L

#91 Revert istio jwt handler
  Makefile
  README.md
  api/v1alpha1/apiRule_types.go
  api/v1alpha1/internal_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/apirule_types.go
  api/v1beta1/internal_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/configmap/configmap.yaml
  config/configmap/kustomization.yaml
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/default/kustomization.yaml
  config/rbac/role.yaml
  controllers/api_controller_integration_test.go
  controllers/api_controller_test.go
  controllers/apirule_controller.go
  controllers/suite_test.go
  hack/security.istio.io_authorizationpolicy.yaml
  hack/security.istio.io_requestauthentication.yaml
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/helpers/config.go
  internal/helpers/default_domain.go
  internal/processing/authorization_policy_helpers.go
  internal/processing/helpers.go
  internal/processing/processing.go
  internal/processing/processing_test.go
  internal/processing/request_authentication_helpers.go
  internal/processing/virtual_service_helpers.go
  internal/types/istio/jwt.go
  internal/validation/dummy.go
  internal/validation/jwt.go
  internal/validation/no_config.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  main.go
Labels: lgtm, area/service-mesh, size/XXL, area/security

#94 Add istio APIRule to samples
  config/samples/istio_v1beta1_apirule.yaml
Labels: lgtm, area/service-mesh, area/security, size/S

#100 Performance tests results
  docs/API Rule performance.md
Labels: lgtm, area/service-mesh, area/security, size/S

#99 Processing restructure
  controllers/apirule_controller.go
  go.mod
  internal/processing/access_rule_processor.go
  internal/processing/access_rule_processor_test.go
  internal/processing/helpers.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/reconciliation.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/ory/access_rule_processor.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/jwt_validator.go
  internal/processing/ory/jwt_validator_test.go
  internal/processing/ory/ory_suite_test.go
  internal/processing/ory/reconciliation.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processing.go
  internal/processing/processing_suite_test.go
  internal/processing/processing_test.go
  internal/processing/reconciliation.go
  internal/processing/reconciliation_test.go
  internal/processing/status.go
  internal/processing/status_test.go
  internal/processing/types.go
  internal/processing/virtual_service_helpers.go
  internal/processing/virtual_service_processor.go
  internal/processing/virtual_service_processor_test.go
  internal/validation/helpers.go
  internal/validation/jwt.go
  internal/validation/labels.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: lgtm, area/service-mesh, size/XXL, area/security

#101 Configure Dependabot for release-1.1
  .github/dependabot.yml
Labels: lgtm, area/security, area/api-gateway, size/S

#108 Update OWNERS
  OWNERS
Labels: lgtm, area/api-gateway, size/S

#110 Bump k8s dependencies
  go.mod
  go.sum
Labels: lgtm, area/api-gateway, size/L
