Repository kyma-project/api-gateway, pull requests merged in 2022-08, with the labels that each got.

#6 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm

#8 Update Readme
  README.md
Labels: lgtm, area/service-mesh, area/security, size/S

#10 Remove JWKS-URI in API-gateway
  Makefile
  README.md
  config/default/manager_args_patch.yaml
  config/default/manager_args_patch.yaml.tmpl
  controllers/apirule_controller.go
  internal/processing/processing.go
  internal/processing/processing_test.go
  main.go
Labels: lgtm, size/M, area/service-mesh, area/security
