Repository kyma-project/api-gateway, pull requests merged in 2022-12, with the labels that each got.

#114 Apply refactoring to istio-jwt branch
  controllers/apirule_controller.go
  internal/processing/access_rule_processor.go
  internal/processing/access_rule_processor_test.go
  internal/processing/authorization_policy_helpers.go
  internal/processing/helpers.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/istio_suite_test.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/processing/istio/reconciliation.go
  internal/processing/istio/request_authentication_processor.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/jwt_validator.go
  internal/processing/ory/jwt_validator_test.go
  internal/processing/ory/ory_suite_test.go
  internal/processing/ory/reconciliation.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processing.go
  internal/processing/processing_suite_test.go
  internal/processing/processing_test.go
  internal/processing/reconciliation.go
  internal/processing/reconciliation_test.go
  internal/processing/request_authentication_helpers.go
  internal/processing/status.go
  internal/processing/status_test.go
  internal/processing/types.go
  internal/processing/virtual_service_helpers.go
  internal/processing/virtual_service_processor.go
  internal/processing/virtual_service_processor_test.go
  internal/validation/dummy.go
  internal/validation/helpers.go
  internal/validation/jwt.go
  internal/validation/labels.go
  internal/validation/no_config.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: lgtm, area/service-mesh, size/XXL, area/security, area/api-gateway

#118 Merge main into feature branch
  .github/dependabot.yml
  OWNERS
  README.md
  controllers/apirule_controller.go
  docs/API Rule performance.md
  go.mod
  go.sum
  internal/processing/helpers.go
  internal/processing/status_test.go
  internal/validation/validate_test.go
Labels: lgtm, area/service-mesh, area/security, size/L

#137 Add comment regarding iss jwt claim validation
  internal/processing/istio/jwt_validator.go
  internal/processing/ory/jwt_validator.go
Labels: lgtm, area/api-gateway, size/XS

#136 Add comment regarding iss jwt claim validation
  internal/processing/ory/jwt_validator.go
Labels: lgtm, area/api-gateway, size/XS

#138 Add principals to Ory/allow APs
  internal/builders/istio.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
Labels: lgtm, size/M, area/api-gateway

#134 Tests for AuthorizationPolicyProcessor and RequestAuthenticationProcessor
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/reconciliation_test.go
  internal/processing/istio/request_authentication_processor.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/reconciliation_test.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processors/access_rule_processor_test.go
  internal/processing/processors/authorization_policy_processor.go
  internal/processing/processors/authorization_policy_processor_test.go
  internal/processing/processors/request_authentication_processor.go
  internal/processing/processors/request_authentication_processor_test.go
  internal/processing/processors/virtual_service_processor_test.go
  internal/processing/types.go
Labels: lgtm, size/XXL, area/api-gateway

#140 Merge from main
  go.mod
  go.sum
  internal/processing/helpers.go
  internal/processing/istio/reconciliation.go
  internal/processing/ory/jwt_validator.go
  internal/processing/ory/reconciliation.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/reconciliation.go
  internal/processing/reconciliation_test.go
  internal/processing/status.go
  internal/validation/validate_test.go
Labels: lgtm, size/M, area/api-gateway

#147 Run reconcilation periodically
  controllers/apirule_controller.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/processing/ory/jwt_validator.go
  internal/processing/ory/jwt_validator_test.go
  internal/validation/validate.go
Labels: lgtm, area/api-gateway, size/L
