Repository kyma-project/api-gateway, pull requests merged in 2022-09, with the labels that each got.

#11 Automated releases
  .github/package.json
  Makefile
  hack/release.sh
Labels: lgtm, size/M, area/service-mesh, area/security

#13 PR to release branch
  hack/release.sh
Labels: lgtm, area/service-mesh, area/security, size/XS

#14 Release 0.1
  .gitignore
  .goreleaser.yaml
  hack/release.sh
Labels: lgtm, size/M, area/service-mesh, area/security

#15 Release script
  .gitignore
  .goreleaser.yaml
  Makefile
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  hack/release.sh
Labels: lgtm, area/service-mesh, area/security, size/L

#16 Quick fix
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, area/service-mesh, area/security, size/S

#17 Fix to release
  Makefile
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  hack/release.sh
Labels: lgtm, size/M, area/service-mesh, area/security

#18 Fix makefile
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/XS

#19 Use git tag for docker image
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/XS

#20 Override tags on ci-release target
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/XS

#22 Automated releases
  .goreleaser.yaml
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/S

#24 Fix image url in release template
  .goreleaser.yaml
Labels: lgtm, area/service-mesh, area/security, size/XS

#25 Important fix
  Dockerfile
Labels: lgtm, area/service-mesh, area/security, size/XS

#26 Add https to image urls
  .goreleaser.yaml
Labels: lgtm, area/service-mesh, area/security, size/XS

#28 Restore docker build and push on PR
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/XS

#31 Look for v1alpha1 resources by label
  internal/processing/processing.go
Labels: lgtm, area/service-mesh, area/security, size/S

#33 Test for fetching by label v1alpha1
  internal/processing/processing_test.go
Labels: lgtm, size/M, area/service-mesh, area/security

#35 Patch label fetching
  internal/processing/processing.go
  internal/processing/processing_test.go
Labels: lgtm, size/M, area/api-gateway

#36 Cherrypick changes from label fetching fix
  internal/processing/processing.go
  internal/processing/processing_test.go
Labels: lgtm, size/M, area/service-mesh, area/security

#39 Don't run formatting on a release
  Makefile
Labels: lgtm, area/service-mesh, area/security, size/XS

#27 Support API Rules on the same path and different methods
  controllers/api_controller_integration_test.go
  internal/processing/helpers.go
  internal/processing/processing.go
  internal/processing/processing_test.go
  internal/processing/virtual_service_helpers.go
  internal/validation/allow.go
  internal/validation/helpers.go
  internal/validation/oauth.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: size/XL, lgtm, area/service-mesh, area/security, area/api-gateway

#29 Add optional `namespace` for `service` in APIRule
  api/v1alpha1/apiRule_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/internal_types.go
  api/v1beta1/apirule_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/internal_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/apirule_controller.go
  internal/helpers/namespace.go
  internal/processing/access_rule_helpers.go
  internal/processing/processing_test.go
  internal/processing/virtual_service_helpers.go
  internal/validation/dummy.go
  internal/validation/jwt.go
  internal/validation/labels.go
  internal/validation/no_config.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: lgtm, area/service-mesh, area/security, size/L
