Repository kyma-project/api-gateway, pull requests merged in 2022-10, with the labels that each got.

#46 Improve convertTo logging
  api/v1alpha1/apirule_conversion.go
  api/v1alpha1/apirule_conversion_test.go
Labels: lgtm, size/M, area/api-gateway

#54 Add additional columns when listing API Rules on the cluster
  api/v1beta1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, area/security, area/api-gateway, size/S

#55 Make Cert Handler CRD Configurable
  cmd/cronjob/cronjob.go
  config/certificates/jobs.yaml
  internal/webhook/certificates.go
Labels: lgtm, size/M, area/service-mesh, area/security

#51 Adding DoD to the issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, area/service-mesh, area/security, size/XS

#58 Dependabot config
  .github/dependabot.yml
  .github/pull-request-template.md
Labels: lgtm, area/service-mesh, area/security, size/S
