Repository kyma-project/api-gateway, pull requests merged in 2023-04, with the labels that each got.

#296 Make integration tests more expressive and increase stability
  Makefile
  controllers/api_controller_integration_test.go
Labels: size/XL, lgtm, area/api-gateway

#295 Adds `fromHeaders` and `fromParams` fields for RequestAuthentication
  api/v1beta1/apirule_types.go
  api/v1beta1/zz_generated.deepcopy.go
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/processing/istio/reconciliation.go
  internal/processing/processors/authorization_policy_processor.go
  internal/validation/authorizations_validation.go
  internal/validation/validate.go
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/istio_jwt_test.go
  tests/integration/manifests/istio-jwt-token-from-headers.yaml
  tests/integration/manifests/istio-jwt-token-from-params.yaml
  tests/integration/scenario_common_jwt_test.go
  tests/integration/scenario_jwt_multiple_mutators_test.go
  tests/integration/scenario_jwt_mutators_overwrite_test.go
  tests/integration/scenario_jwt_token_from_test.go
  tests/integration/scripts/code-coverage-guard.sh
  tests/integration/test_helpers.go
Labels: size/XL, lgtm, area/api-gateway

#300 Allow exposure of endpoints with wildcard `/*` and `/.*` in Istio JWT
  internal/builders/virtual_service.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/istio_jwt_test.go
  tests/integration/manifests/istio-jwt-common.yaml
  tests/integration/scenario_common_jwt_test.go
  tests/integration/test_helpers.go
Labels: lgtm, area/api-gateway, size/L

#303 Adapt api-gateway-controller registry
  .goreleaser.yaml
Labels: do-not-merge/hold, lgtm, area/api-gateway, size/XS

#304 Use new image registry
  Makefile
Labels: lgtm, area/api-gateway, size/XS

#318 Update Dockerfile-certificates
  Dockerfile
  Dockerfile-certificates
Labels: lgtm, area/api-gateway, size/XS

#319 Add requestPrincipal with issuer
  controllers/api_controller_integration_test.go
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/processing/helpers.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
Labels: lgtm, size/M, area/api-gateway

#324 Add info about requestPrincipals creation
  docs/istio-jwt.md
Labels: lgtm, area/api-gateway, size/XS

#323 Port Custom Domain test to API-Gateway
  Makefile
  tests/integration/README.md
  tests/integration/env_vars_custom_domain.sh
  tests/integration/features/custom-domain/custom_domain.feature
  tests/integration/istio_jwt_test.go
  tests/integration/main_test.go
  tests/integration/manifests/custom-domain/no-access-strategy.yaml
  tests/integration/manifests/custom-domain/oauth-strategy.yaml
  tests/integration/manifests/custom-domain/resources.yaml
  tests/integration/manifests/custom-domain/testing-app.yaml
  tests/integration/scenario_custom_domain_test.go
  tests/integration/scenario_jwt_multiple_mutators_test.go
  tests/integration/scenario_jwt_mutators_overwrite_test.go
  tests/integration/test_helpers.go
Labels: size/XL, lgtm, area/api-gateway

#325 Update docs for tokenFrom JWT feature
  docs/istio-jwt.md
Labels: lgtm, size/M, area/api-gateway

#331 Create adr.md issue template
  .github/ISSUE_TEMPLATE/adr.md
Labels: lgtm, area/api-gateway, size/S

#326 APIRule CR technical reference docs
  docs/api-rule-cr.md
  docs/istio-jwt.md
Labels: lgtm, area/api-gateway, size/L

#332 Custom domain tests updates
  tests/integration/README.md
Labels: lgtm, area/api-gateway, size/S

#333 Bump Go to 1.20.3
  Dockerfile
  Dockerfile-certificates
Labels: lgtm, area/api-gateway, size/XS
