Repository kyma-project/api-gateway, pull requests merged in 2023-11, with the labels that each got.

#695 Fix object already modified error
  controllers/gateway/apirule_controller.go
Labels: lgtm, size/M

#694 Show warning on HTTP
  config/ui-extensions/apirules/details
  config/ui-extensions/apirules/form
  config/ui-extensions/apirules/translations
Labels: lgtm, size/S

#696 Update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#701 Add ory to modular sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#704 Add dummy Azure pipeline
  .github/.azure-pipeline/azure-pipelines.yaml
Labels: lgtm, size/S

#712 Remove vulnerability check from PRs
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/XS

#713 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#711 Fix a sidebar
  docs/user/custom-resources/_sidebar.md
Labels: lgtm, size/XS

#691 UI tests
  .github/workflows/ui-tests.yaml
  tests/ui/.gitignore
  tests/ui/tests/README.md
  tests/ui/tests/config.js
  tests/ui/tests/cypress.config.js
  tests/ui/tests/fixtures/.gitignore
  tests/ui/tests/package-lock.json
  tests/ui/tests/package.json
  tests/ui/tests/plugins/index.js
  tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
  tests/ui/tests/scripts/k3d-local-dev.sh
  tests/ui/tests/support/exceptions.js
  tests/ui/tests/support/index.js
  tests/ui/tests/support/loadFile.js
  tests/ui/tests/support/login.js
  tests/ui/tests/support/navigation.js
  tests/ui/tests/support/random.js
  tests/ui/tests/support/views/index.js
  tests/ui/tests/support/views/namespace.js
  tests/ui/tests/support/views/service.js
  tests/ui/tests/tests/api-rule/test-api-rules.spec.js
Labels: lgtm, size/XXL

#722 Update dependabot config to ignore istio packages
  .github/dependabot.yml
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/S

#700 Omid bump in Kyma as DoD and add check on OS
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS

#734 Update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#729 Run UI tests on CRD changes
  .github/workflows/ui-tests.yaml
Labels: lgtm, size/XS

#737 Make [].services not required
  config/ui-extensions/apirules/form
Labels: lgtm, size/XS

#741 Update APIRule documentation link
  config/ui-extensions/apirules/general
Labels: lgtm, size/XS

#740 Update README.md
  README.md
Labels: lgtm, size/XS

#744 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#743 Limit reconciled APIGateway CRs to only one
  Makefile
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_test.go
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  tests/integration/testsuites/gateway/features/kyma_gateway.feature
  tests/integration/testsuites/gateway/manifests/api-gateway.yaml
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/L

#746 Remove Azure pipeline
  .github/.azure-pipeline/azure-pipelines.yaml
Labels: lgtm, size/S

#745 Cleanup jobs after modularisation
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
  Makefile
  hack/kyma-components.yaml
  tests/integration/scripts/custom-domain-gardener.sh
  tests/integration/scripts/test-gardener.sh
Labels: lgtm, size/L

#747 Remove reference to no longer existing job in gh actions
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS

#738 Technical design for CORS policy
  docs/contributor/04-40-cors-policy-design.md
Labels: lgtm, size/M, cla: yes
