Repository kyma-project/api-gateway, pull requests merged in 2023-10, with the labels that each got.

#576 Fix ref
  .github/actions/upgrade-test/action.yaml
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/S

#537 Add Kyma Gateway
  Makefile
  apis/operator/v1alpha1/apigateway_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_apigateways.yaml
  config/rbac/role.yaml
  config/samples/operator_v1alpha1_apigateway.yaml
  controllers/gateway/types.go
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_types.go
  controllers/operator/status.go
  controllers/operator/status_test.go
  controllers/operator/suite_test.go
  controllers/status.go
  controllers/status_test.go
  controllers/suite_test.go
  docs/assets/kyma-gateway-resources-gardener.svg
  docs/assets/kyma-gateway-resources-os.svg
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
  go.mod
  go.sum
  hack/cert.gardener.cloud_certificate.yaml
  hack/dns.gardener.cloud_dnsentry.yaml
  internal/gateway/certificate.go
  internal/gateway/certificate.yaml
  internal/gateway/certificate_secret.go
  internal/gateway/certificate_secret.yaml
  internal/gateway/certificate_test.go
  internal/gateway/dns_entry.go
  internal/gateway/dns_entry.yaml
  internal/gateway/dns_entry_test.go
  internal/gateway/finalizer.go
  internal/gateway/gardener.go
  internal/gateway/gardener_test.go
  internal/gateway/gateway.go
  internal/gateway/kyma_gateway.go
  internal/gateway/kyma_gateway.yaml
  internal/gateway/kyma_gateway_test.go
  internal/gateway/resource.go
  internal/gateway/resource_test.go
  internal/gateway/suite_test.go
  main.go
  tests/ginkgo_reporter.go
Labels: kind/feature, lgtm, size/XXL, area/api-gateway

#577 Revert "Fix ref (#576)"
  .github/actions/upgrade-test/action.yaml
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/S

#568 Update issue templates
  .github/ISSUE_TEMPLATE/deprecation_deletion.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/M, area/api-gateway

#588 Temporarily remove upgrade test from workflows
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/M

#590 Release workflow waiting for rel prow jobs
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS

#591 Edit formatting
  docs/contributor/04-10-technical-design.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
Labels: lgtm, size/XS

#574 Pipelines docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M

#601 fix make target
  Makefile
  tests/integration/env_vars.sh
  tests/integration/env_vars_custom_domain.sh
Labels: lgtm, size/XS

#602 Use pull request ref in PR tests
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/XS

#613 Enable Gateway integration tests
  Makefile
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/S

#622 Extend cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/S

#621 fix bug in workflow
  .github/workflows/main-integration.yaml
  tests/ginkgo_reporter.go
Labels: lgtm, size/XS

#567 API-Gateway module CR blocking deletion
  Dockerfile
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_controller_test.go
  controllers/operator/suite_test.go
  docs/contributor/04-10-technical-design.md
  internal/reconciliations/gateway/certificate_secret.go
  internal/reconciliations/gateway/certificate_test.go
  internal/reconciliations/gateway/dns_entry.go
  internal/reconciliations/gateway/dns_entry_test.go
  internal/reconciliations/gateway/finalizer.go
  internal/reconciliations/gateway/gateway.go
  internal/reconciliations/gateway/kyma_gateway.go
  internal/reconciliations/gateway/kyma_gateway_test.go
  internal/reconciliations/gateway/resource_test.go
  internal/reconciliations/gateway/suite_test.go
  internal/reconciliations/gateway/test_assets/test_controlled_resource_list.yaml
  internal/resources/resource_suite_test.go
  internal/resources/resources.go
  internal/resources/resources_test.go
  internal/resources/test_assets/test_resources_list.yaml
  internal/resources/test_assets/test_wrong_resources_list.yaml
  main.go
  manifests/controlled_resources_list.yaml
  tests/ginkgo_reporter.go
  tests/integration/jwt_handler.go
  tests/integration/pkg/client/client.go
  tests/integration/pkg/hooks/hooks.go
  tests/integration/pkg/hooks/manifests/api-gateway.yaml
  tests/integration/pkg/testcontext/config.go
  tests/integration/test_report.go
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/custom-domain/testsuite.go
  tests/integration/testsuites/gateway/features/custom_resource_deletion.feature
  tests/integration/testsuites/gateway/features/kyma_gateway.feature
  tests/integration/testsuites/gateway/features/kyma_gateway_gardener.feature
  tests/integration/testsuites/gateway/features/kyma_gateway_k3d.feature
  tests/integration/testsuites/gateway/manifests/apirule.yaml
  tests/integration/testsuites/gateway/manifests/virtual-service.yaml
  tests/integration/testsuites/gateway/scenario.go
  tests/integration/testsuites/gateway/testsuite.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/testsuite.go
  tests/integration/testsuites/upgrade/testsuite.go
Labels: lgtm, size/XXL

#626 Add virtual service for monitoring
  controllers/operator/suite_test.go
  docs/assets/kyma-gateway-resources-gardener.svg
  docs/assets/kyma-gateway-resources-os.svg
  docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
  internal/reconciliations/gateway/kyma_gateway.go
  internal/reconciliations/gateway/kyma_gateway_test.go
  internal/reconciliations/gateway/suite_test.go
  internal/reconciliations/gateway/virtual_service.go
  internal/reconciliations/gateway/virtual_service.yaml
  internal/reconciliations/gateway/virtual_service_test.go
  internal/reconciliations/suite_test.go
  manifests/controlled_resources_list.yaml
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/gateway/features/kyma_gateway_gardener.feature
  tests/integration/testsuites/gateway/features/kyma_gateway_k3d.feature
Labels: lgtm, size/L

#624 ui extension
  config/default/kustomization.yaml
  config/ui-extensions/apigateways/details
  config/ui-extensions/apigateways/form
  config/ui-extensions/apigateways/general
  config/ui-extensions/apigateways/kustomization.yaml
  config/ui-extensions/apigateways/list
  config/ui-extensions/apigateways/translations
  config/ui-extensions/kustomization.yaml
Labels: lgtm, size/M

#632 Fix actions on main
  .github/workflows/main-integration.yaml
  Makefile
  hack/kyma-components-no-istio.yaml
  hack/kyma-components.yaml
Labels: lgtm, size/XS

#635 Add missing release branch trigger for Pull Request workflow
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS

#627 ORY Oathkeeper Rules block API-Gateway CR deletion
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_controller_test.go
  controllers/operator/suite_test.go
  docs/contributor/04-10-technical-design.md
  internal/reconciliations/oathkeeper/crd.go
  tests/integration/pkg/client/client.go
  tests/integration/pkg/hooks/hooks.go
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/gateway/features/deletion.feature
  tests/integration/testsuites/gateway/manifests/kyma-gateway-enabled.yaml
  tests/integration/testsuites/gateway/manifests/oryrule.yaml
  tests/integration/testsuites/gateway/scenario.go
  tests/integration/testsuites/gateway/testsuite.go
Labels: lgtm, size/L

#634 Add release notes and version
  VERSION
  docs/release-notes/2.0.0-rc.md
Labels: lgtm, size/XS

#633 update cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M

#640 k8s compatibility check
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/M

#641 Add Kubernetes compatibility tests
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/pull-integration.yaml
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/L

#642 update busola link and move ui-extensions from mod-dev
  config/default/kustomization.yaml
  config/ui-extensions/apigateways/details
  config/ui-extensions/apigateways/form
  config/ui-extensions/apigateways/general
  config/ui-extensions/apigateways/kustomization.yaml
  config/ui-extensions/apigateways/list
  config/ui-extensions/apigateways/translations
  config/ui-extensions/kustomization.yaml
Labels: lgtm, size/M

#643 Add version and release notes
  VERSION
  docs/release-notes/2.0.0-rc.md
Labels: lgtm, size/XS

#645 udpate sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#628 Wait for dependencies in APIRule and API Gateway
  apis/gateway/v1beta1/apirule_types.go
  controllers/gateway/api_controller_test.go
  controllers/gateway/apirule_controller.go
  controllers/gateway/apirule_controller_validation_integration_test.go
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller.go
  controllers/operator/suite_test.go
  controllers/status.go
  docs/contributor/01-20-api-gateway-dependencies.md
  docs/contributor/01-30-api-rule-dependencies.md
  internal/dependencies/dependencies.go
  internal/dependencies/dependencies_suite_test.go
  internal/dependencies/dependencies_test.go
  internal/validation/validate.go
  main.go
  tests/integration/pkg/hooks/hooks.go
Labels: size/XL, lgtm

#647 disable deleting and creating APIGateway CR
  config/ui-extensions/apigateways/general
Labels: lgtm, size/XS

#649 Update diagrams
  docs/assets/kyma-gateway-resources-gardener.svg
  docs/assets/kyma-gateway-resources-os.svg
Labels: lgtm, size/XS

#652 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#654 Revert "change trigger to pull_request"
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/XS

#653 Upgrade test job
  .github/actions/upgrade-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
  Makefile
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
  tests/integration/testsuites/upgrade/scenario.go
Labels: lgtm, size/L

#657 Update Gardener certificate name to "kyma-tls-cert"
  internal/reconciliations/gateway/certificate.go
  tests/integration/testsuites/gateway/features/kyma_gateway_gardener.feature
Labels: lgtm, size/XS

#658 Release notes for 2.0.0 release
  README.md
  docs/contributor/01-00-installation.md
  docs/release-notes/2.0.0.md
  docs/release-notes/template.md
Labels: lgtm, size/M

#665 Run upgrade tests on PRs with PR codebase
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/XS

#648 Add sidebars, update the README files
  README.md
  docs/api-rule-cr.md
  docs/contributor/01-00-installation.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/custom-resources/README.md
  docs/user/custom-resources/_sidebar.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  docs/user/custom-resources/apigateway/_sidebar.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/custom-resources/apirule/04-40-apirule-mutators.md
  docs/user/custom-resources/apirule/README.md
  docs/user/custom-resources/apirule/_sidebar.md
  docs/user/technical-reference/05-00-api-gateway-operator-parameters.md
  docs/user/technical-reference/README.md
  docs/user/technical-reference/_sidebar.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-00-apigateway-connect-api-rule.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-01-401-unauthorized-403-forbidden.md
  docs/user/troubleshooting-guides/_sidebar.md
  docs/user/tutorials/01-60-security/01-61-mtls-selfsign-client-certicate.md
  docs/user/tutorials/_sidebar.md
Labels: lgtm, size/L

#662 Remove flakiness from upgrade test
  tests/integration/testsuites/upgrade/features/upgrade.feature
  tests/integration/testsuites/upgrade/scenario.go
Labels: lgtm, size/M

#670 Fix checkout on PR upgrade-test
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/create-release.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
Labels: lgtm, size/M

#672 Release API Gateway 2.0.0
  VERSION
Labels: lgtm, size/XS

#673 Add dependabot config for release-2.0 branch
  .github/dependabot.yml
Labels: lgtm, size/M

#681 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/M

#684 Get latest build commit for main scheduled workflow via script
  .github/workflows/main-integration.yaml
  scripts/get_latest_build_sha.sh
Labels: lgtm, size/M

#683 Add gateway integration tests to pipeline
  tests/integration/scripts/custom-domain-gardener-aws.sh
  tests/integration/scripts/custom-domain-gardener-gcp.sh
  tests/integration/scripts/custom-domain-gardener.sh
Labels: lgtm, size/S

#686 Create vulnerabilities-check.yaml
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/M

#663 API Gateway module migration script
  hack/managed-kyma-migration/README.md
  hack/managed-kyma-migration/managed-kyma-migration.sh
Labels: lgtm, size/L

#688 Don't deploy kyma-system
  Makefile
  README.md
  config/manager/manager.yaml
  docs/contributor/01-00-installation.md
Labels: lgtm, size/M

#690 Copy APIRules ui + add token_from
  config/ui-extensions/apirules/dataSources
  config/ui-extensions/apirules/details
  config/ui-extensions/apirules/form
  config/ui-extensions/apirules/general
  config/ui-extensions/apirules/kustomization.yaml
  config/ui-extensions/apirules/list
  config/ui-extensions/apirules/presets
  config/ui-extensions/apirules/translations
  config/ui-extensions/kustomization.yaml
Labels: lgtm, size/L
