Repository kyma-project/api-gateway, pull requests merged in 2023-09, with the labels that each got.

#496 Remove api-gateway-config cm
  config/configmap/configmap.yaml
  config/configmap/kustomization.yaml
  config/default/kustomization.yaml
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/suite_test.go
Labels: lgtm, size/L

#497 Add kyma-install again
  Makefile
  hack/kyma-components.yaml
Labels: lgtm, size/S

#494 API Gateway upgrade test
  .github/actions/upgrade-integration-test/action.yaml
  .github/actions/wait-for-job-suceed-or-fail/action.yaml
  .github/workflows/integration-tests.yaml
  Makefile
  config/samples/api-gateway-confimap.yaml
  go.mod
  go.sum
  tests/integration/main_test.go
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/pkg/resource/manager.go
  tests/integration/pkg/testcontext/config.go
  tests/integration/testsuites/upgrade/features/upgrade.feature
  tests/integration/testsuites/upgrade/manifests/global-commons.yaml
  tests/integration/testsuites/upgrade/manifests/istio-jwt-common.yaml
  tests/integration/testsuites/upgrade/manifests/testing-app.yaml
  tests/integration/testsuites/upgrade/scenario.go
  tests/integration/testsuites/upgrade/testsuite.go
Labels: size/XL, lgtm, area/api-gateway

#506 Makefile adjustments and helper scripts
  Makefile
  hack/build_and_push_locally.sh
  hack/download_module_image.sh
Labels: lgtm, size/M

#481 Create API-Gateway-CRD-proposal.md
  docs/contributor/01-10-API-Gateway-CRD-proposal.md
Labels: lgtm, area/api-gateway, size/L

#513 Refactor and PR workflow test
  .github/workflows/pull_request.yaml
  tests/integration/scripts/code-coverage-guard.sh
Labels: lgtm, size/XS

#517 Bump dependencies
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, size/L

#523 Release on mod-dev: initial workflow and scripts
  .github/workflows/create-release.yaml
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_assets.sh
  scripts/publish_release.sh
Labels: lgtm, size/L

#525 Trigger manager image build
  internal/helpers/common.go
Labels: lgtm, size/XS

#508 Fix integration test workflow
  .github/workflows/integration-tests.yaml
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, area/api-gateway, size/S

#515 Discover default domain from gateway
  Makefile
  config/rbac/role.yaml
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/api_controller_test.go
  controllers/gateway/apirule_controller.go
  controllers/gateway/apirule_controller_validation_integration_test.go
  controllers/gateway/suite_test.go
  controllers/gateway/types.go
  controllers/operator/apigateway_controller.go
  docs/assets/operator-contributor-skr-overview.svg
  docs/contributor/04-10-technical-design.md
  go.mod
  go.sum
  hack/networking.istio.io_gateways.yaml
  internal/helpers/default_domain.go
  internal/processing/default_domain/default_domain.go
  internal/processing/default_domain/default_domain_test.go
  internal/processing/istio/reconciliation.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/ory/reconciliation.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/processors/access_rule_processor.go
  internal/processing/types.go
  internal/validation/validate.go
  main.go
Labels: size/XL, lgtm

#531 Fix integration test pipeline #2
  .github/actions/wait-for-job-succeed-or-fail/action.yaml
  .github/workflows/integration-tests.yaml
Labels: lgtm, area/api-gateway, size/XS

#536 Fix oauth2 scenarios in ory jwt
  tests/integration/pkg/auth/hydra.go
  tests/integration/testsuites/ory/manifests/global-commons.yaml
  tests/integration/testsuites/ory/manifests/hydra-client.yaml
  tests/integration/testsuites/ory/manifests/jwt-oauth-one-path-strategy.yaml
  tests/integration/testsuites/ory/manifests/jwt-oauth-strategy.yaml
  tests/integration/testsuites/ory/manifests/oauth-strategy.yaml
  tests/integration/testsuites/ory/manifests/secured-to-unsecured.yaml
  tests/integration/testsuites/ory/manifests/unsecured-to-secured-2.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_oauth2_jwt_one_path.go
  tests/integration/testsuites/ory/testsuite.go
Labels: lgtm, area/api-gateway, size/L

#526 Configure sec-scanner
  sec-scanners-config.yaml
Labels: lgtm, area/api-gateway, size/S

#507 CI Makefile slightly changed (shortened)
  hack/ci/Makefile
Labels: lgtm, size/S

#539 Empty/stub release workflow for testing purposes
  .github/workflows/create-release.yaml
Labels: lgtm, area/api-gateway, size/S

#516 APIRule v1alpha1 removal
  Dockerfile-certificates
  Makefile
  api/v1alpha1/apiRule_types.go
  api/v1alpha1/apirule_conversion.go
  api/v1alpha1/apirule_conversion_test.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/apirule_webhook.go
  cmd/cronjob/cronjob.go
  config/certificates/jobs.yaml
  config/certificates/kustomization.yaml
  config/certificates/rbac.yaml
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/default/kustomization.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  internal/processing/helpers.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/request_authentication_processor.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processors/access_rule_processor.go
  internal/processing/processors/access_rule_processor_test.go
  internal/processing/processors/virtual_service_processor_test.go
  internal/validation/validate.go
  internal/webhook/certificates.go
  main.go
Labels: lgtm, size/XXL, area/api-gateway

#540 Stub of release-notes for testing purposes
  docs/release-notes/0.0.1-dev.md
Labels: lgtm, size/XS

#544 Use jobguard from path
  Makefile
  tests/integration/scripts/jobguard.sh
Labels: lgtm, area/api-gateway, size/XS

#547 Add workflow dispatch for main integration workflow
  .github/workflows/main-integration.yaml
Labels: area/api-gateway, size/XS

#548 Typos, messages and improvements regarding module building
  Makefile
  hack/ci/Makefile
  scripts/create_draft_release.sh
Labels: lgtm, size/S

#553 sed corrected, additional target to get latest release version
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/S

#554 GHA main workflow definition fixed
  .github/workflows/main-integration.yaml
Labels: lgtm, area/api-gateway, size/XS

#555 Environment for GHA
  .github/workflows/pull-integration.yaml
Labels: lgtm, area/api-gateway, size/XS

#557 Make install needs kustomize
  Makefile
  hack/kyma-components.yaml
Labels: lgtm, area/api-gateway, size/S

#558 Fixed slack notifications on main workflow
  .github/workflows/main-integration.yaml
  Makefile
Labels: lgtm, area/api-gateway, size/XS

#564 Fix nightly scheduled integration tests
  .github/workflows/main-integration.yaml
  Makefile
Labels: lgtm, area/api-gateway, size/S

#565 Adjust custom domain test's deploy to gardener
  tests/integration/scripts/custom-domain-gardener.sh
Labels: lgtm, size/XS

#573 fix workflow bugs
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS
