Repository kyma-project/api-gateway, pull requests merged in 2023-06, with the labels that each got.

#374 Update code owners
  CODEOWNERS
Labels: lgtm, area/api-gateway, size/XS

#365 Use cluster specifics from env vars, wait for shoot reconcile
  tests/integration/scripts/integration-gardener-custom-domain.sh
Labels: lgtm, area/api-gateway, size/L

#375 Add forwardOriginalToken true to istio's JWTRule
  internal/builders/istio.go
  internal/builders/istio_test.go
Labels: lgtm, area/api-gateway, size/XS

#392 Enable godog Strict mode
  tests/integration/main_test.go
Labels: lgtm, area/api-gateway, size/XS

#395 Bump golang to version 1.20.5
  Dockerfile
  Dockerfile-certificates
Labels: lgtm, area/api-gateway, size/XS

#394 Bump golang to version 1.20.5
  Dockerfile
  Dockerfile-certificates
Labels: lgtm, area/api-gateway, size/XS

#396 Remove binaries from release
  .goreleaser.yaml
Labels: lgtm, area/api-gateway, size/S

#397 Remove binaries from release
  .goreleaser.yaml
Labels: lgtm, area/api-gateway, size/S

#398 Skip release builds
  .goreleaser.yaml
Labels: lgtm, area/api-gateway, size/XS

#399 Skip release builds
  .goreleaser.yaml
Labels: lgtm, area/api-gateway, size/XS

#400 Update jobguard.sh
  tests/integration/scripts/jobguard.sh
Labels: lgtm, area/api-gateway, size/XS

#401 Update jobguard.sh
  tests/integration/scripts/jobguard.sh
Labels: lgtm, area/api-gateway, size/XS

#402 Validate label selector only in Istio JWT
  controllers/apirule_controller.go
  internal/helpers/common.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: kind/bug, lgtm, size/M, area/api-gateway

#405 Fix label selectors validation in 1.7 release
  controllers/apirule_controller.go
  internal/helpers/common.go
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: lgtm, size/M, area/api-gateway

#407 Wait only for build jobs on release
  hack/release.sh
Labels: lgtm, area/api-gateway, size/XS

#406 Wait only for build jobs on release
  hack/release.sh
Labels: lgtm, area/api-gateway, size/XS

#403 Restructure integration test scripts
  tests/integration/env_vars.sh
  tests/integration/env_vars_custom_domain.sh
  tests/integration/pkg/helpers/string.go
  tests/integration/pkg/testcontext/config.go
  tests/integration/scripts/custom-domain-gardener-aws.sh
  tests/integration/scripts/custom-domain-gardener-gcp.sh
  tests/integration/scripts/custom-domain-gardener.sh
  tests/integration/scripts/jobguard.sh
  tests/integration/scripts/provision-gardener.sh
  tests/integration/scripts/test-gardener-aws.sh
  tests/integration/scripts/test-gardener-gcp.sh
  tests/integration/scripts/test-gardener.sh
  tests/integration/testsuites/custom-domain/scenario.go
Labels: lgtm, area/api-gateway, size/L
