Repository kyma-project/api-gateway, pull requests merged in 2023-12, with the labels that each got.

#751 Oathkeeper Maester resources first-time reconciliation failure
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_test.go
  controllers/operator/apigateway_types.go
  controllers/operator/suite_test.go
  internal/reconciliations/oathkeeper/crd.go
  internal/reconciliations/oathkeeper/deployment.go
  internal/reconciliations/oathkeeper/deployment_test.go
  internal/reconciliations/oathkeeper/hpa_test.go
  internal/reconciliations/oathkeeper/maester/cluster_role.go
  internal/reconciliations/oathkeeper/maester/maester.go
  internal/reconciliations/oathkeeper/oathkeeper.go
  internal/reconciliations/oathkeeper/oathkeeper_test.go
  internal/reconciliations/oathkeeper/suite_test.go
  main.go
Labels: size/XL, lgtm, cla: yes

#758 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#759 Use collaborator check only on `wait for image build`
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/XS, cla: yes

#761 Add one main sidebar
  README.md
  docs/user/_sidebar.md
  docs/user/custom-resources/_sidebar.md
  docs/user/custom-resources/apigateway/_sidebar.md
  docs/user/custom-resources/apirule/_sidebar.md
  docs/user/technical-reference/_sidebar.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-00-basic-diagnostics.md
  docs/user/troubleshooting-guides/03-10-dns-mgt/README.md
  docs/user/troubleshooting-guides/_sidebar.md
  docs/user/tutorials/01-40-expose-workload/README.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/README.md
  docs/user/tutorials/01-60-security/README.md
  docs/user/tutorials/README.md
  docs/user/tutorials/_sidebar.md
Labels: lgtm, size/L, cla: yes

#762 Correct the README
  README.md
  docs/user/README.md
Labels: lgtm, size/S, cla: yes

#764 Include istio-injection label when creating kyma-system ns
  Makefile
  README.md
  controllers/operator/apigateway_controller.go
Labels: lgtm, size/XS, cla: yes

#768 Add additional information about APIGateway CR
  docs/contributor/04-10-technical-design.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
Labels: lgtm, size/M, cla: yes

#772 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#760 Allow configuring CORS on APIRule
  .github/workflows/ui-tests.yaml
  apis/gateway/v1beta1/apirule_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/ui-extensions/apirules/dataSources
  config/ui-extensions/apirules/details
  config/ui-extensions/apirules/form
  config/ui-extensions/apirules/translations
  docs/release-notes/2.1.0.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/testsuites/istio-jwt/features/cors.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-custom-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/istio-default-cors.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_custom_cors.go
  tests/integration/testsuites/istio-jwt/scenario_default_cors.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/features/cors.feature
  tests/integration/testsuites/ory/manifests/custom-cors.yaml
  tests/integration/testsuites/ory/manifests/default-cors.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_custom_cors.go
  tests/integration/testsuites/ory/scenario_default_cors.go
  tests/integration/testsuites/ory/testsuite.go
  tests/ui/tests/cypress.config.js
  tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
  tests/ui/tests/support/combobox.js
  tests/ui/tests/support/filter.js
  tests/ui/tests/support/index.js
  tests/ui/tests/support/login.js
  tests/ui/tests/support/navigation.js
  tests/ui/tests/support/views/namespace.js
  tests/ui/tests/support/views/service.js
  tests/ui/tests/tests/api-rule/test-api-rules.spec.js
Labels: lgtm, size/XXL, cla: yes

#775 Remove ModuleTemplate leftovers
  .github/workflows/create-release.yaml
  Makefile
  docs/contributor/04-30-ci-cd.md
  hack/local/Makefile
  hack/local/api-gateway/Makefile
  hack/local/api-gateway/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
Labels: lgtm, size/L, cla: yes

#769 Restrict access to methods for allow access strategy
  apis/gateway/v1beta1/apirule_types.go
  apis/gateway/v1beta1/rule.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_timeout_integration_test.go
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller_integration_test.go
  docs/release-notes/2.1.0.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  internal/builders/access_rule.go
  internal/builders/access_rule_test.go
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/istio_suite_test.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/testsuites/istio-jwt/features/expose_methods_on_paths.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-custom-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/istio-default-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_multiple_mutators.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_mutators_overwrite.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/features/expose_methods_on_paths.feature
  tests/integration/testsuites/ory/manifests/custom-cors.yaml
  tests/integration/testsuites/ory/manifests/default-cors.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/ory/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#777 Remove module template related docs
  docs/contributor/01-00-installation.md
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/S, cla: yes

#780 Fix watch issue with Ory Rules
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_test.go
Labels: lgtm, size/M, cla: yes

#789 Fix release branch integration tests
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
  Makefile
  hack/kyma-components.yaml
  tests/integration/scripts/custom-domain-gardener.sh
  tests/integration/scripts/test-gardener.sh
Labels: lgtm, size/L, cla: yes
