Repository kyma-project/api-gateway, pull requests merged in 2023-08, with the labels that each got.

#442 Provide support for configuring request timeout in APIRule
  api/v1beta1/apirule_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/api_controller_integration_test.go
  controllers/apirule_timeout_integration_test.go
  controllers/types.go
  docs/api-rule-cr.md
  internal/builders/virtual_service_test.go
  internal/helpers/config.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processors/virtual_service_processor.go
  internal/processing/processors/virtual_service_processor_test.go
  internal/processing/types.go
  internal/validation/validate.go
  internal/validation/validate_test.go
Labels: size/XL, lgtm, area/api-gateway

#444 Update CRD as in kyma-project/kyma repo
  .github/dependabot.yml
  api/v1alpha1/apiRule_types.go
  api/v1beta1/apirule_types.go
  config/crd/apirules.gateway.crd.yaml
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: size/XL, lgtm, area/api-gateway

#456 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, area/api-gateway, size/L

#466 Change integration tests config for aws
  tests/integration/scripts/test-gardener-aws.sh
  tests/integration/scripts/test-gardener.sh
Labels: lgtm, area/api-gateway, size/S

#461 Update K8s deps to latest
  go.mod
  go.sum
Labels: lgtm, area/api-gateway, size/L

#482 Add grouping for Kubernetes PRs in Dependabot
  .github/dependabot.yml
Labels: lgtm, area/api-gateway, size/XS
