Repository kyma-project/api-gateway, pull requests merged in 2023-02, with the labels that each got.

#193 Add predicate to not reconcile on status update
  controllers/apirule_controller.go
  go.work.sum
Labels: lgtm, area/api-gateway, size/S

#192 Add Istio JWT tests with scopes
  .gitignore
  api/v1beta1/zz_generated.deepcopy.go
  tests/integration/README.md
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/istio_jwt_test.go
  tests/integration/main_test.go
  tests/integration/manifests/istio-jwt-scopes-happy.yaml
  tests/integration/manifests/istio-jwt-scopes-unhappy.yaml
  tests/integration/pkg/jwt/auth.go
  tests/integration/test_helpers.go
Labels: lgtm, area/api-gateway, size/L

#195 Bump to 1.3
  .github/dependabot.yml
Labels: lgtm, area/api-gateway, size/XS

#197 Add support for audiences
  api/v1beta1/apirule_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/samples/istio_v1beta1_apirule.yaml
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/processing/istio/audience_test.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/request_authentication_processor.go
Labels: lgtm, area/api-gateway, size/L

#200 Update istio-jwt docs with AUD
  docs/istio-jwt.md
Labels: lgtm, area/api-gateway, size/XS

#201 Use aud claim instead of audiences
  internal/processing/istio/audience_test.go
  internal/processing/istio/authorization_policy_processor.go
Labels: lgtm, area/api-gateway, size/S

#202 Test for Istio JWT audiences
  .gitignore
  go.work.sum
  tests/integration/README.md
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/istio_jwt_test.go
  tests/integration/main_test.go
  tests/integration/manifests/istio-jwt-audiences.yaml
  tests/integration/manifests/istio-jwt-common.yaml
  tests/integration/manifests/istio-jwt-scopes-happy.yaml
  tests/integration/manifests/istio-jwt-scopes-unhappy.yaml
  tests/integration/manifests/istio-jwt-scopes.yaml
  tests/integration/pkg/helpers/helpers.go
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/pkg/resource/manager.go
  tests/integration/scenario_audience_test.go
  tests/integration/scenario_common_jwt_test.go
  tests/integration/scenario_scopes_test.go
  tests/integration/test_helpers.go
Labels: size/XL, lgtm, area/api-gateway

#204 Automate manual tests
  tests/integration/env_vars.sh
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/istio_jwt_test.go
  tests/integration/main_test.go
  tests/integration/manifests/global-commons.yaml
  tests/integration/manifests/istio-jwt-and-unrestricted.yaml
  tests/integration/manifests/istio-jwt-service-fallback.yaml
  tests/integration/manifests/istio-jwt-two-namespaces.yaml
  tests/integration/manifests/second-namespace.yaml
  tests/integration/manifests/testing-app.yaml
  tests/integration/scenario_audience_test.go
  tests/integration/scenario_common_jwt_test.go
  tests/integration/scenario_jwt_and_unrestricted_test.go
  tests/integration/scenario_jwt_two_namespaces_test.go
  tests/integration/scenario_scopes_test.go
  tests/integration/scenario_service_fallback_test.go
  tests/integration/test_helpers.go
Labels: lgtm, area/api-gateway, size/L

#208 Reduce flakiness of integration tests
  controllers/api_controller_integration_test.go
  controllers/apirule_controller_status_integration_test.go
  controllers/reconciliation_test/api_controller_integration_test.go
  controllers/suite_test.go
Labels: lgtm, area/api-gateway, size/L

#205 OAuth2 and Istio JWT test
  go.work.sum
  tests/integration/features/istio-jwt/Istio_jwt_two_strategies.feature
  tests/integration/istio_jwt_test.go
  tests/integration/manifests/istio-jwt-and-oauth.yaml
  tests/integration/pkg/jwt/auth.go
  tests/integration/scenario_audience_test.go
  tests/integration/scenario_oauth_and_jwt_test.go
  tests/integration/scenario_scopes_test.go
  tests/integration/test_helpers.go
Labels: lgtm, area/api-gateway, size/L

#206 Add installation of Kyma and provisioning k3d to Makefile
  Makefile
  hack/kyma-components.yaml
  tests/integration/main_test.go
  tests/integration/pkg/helpers/helpers.go
Labels: lgtm, size/M, area/api-gateway

#215 Audiences validation
  controllers/apirule_controller_validation_integration_test.go
  go.work.sum
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/validation/authorizations_validation.go
Labels: lgtm, area/api-gateway, size/L

#218 Add test audiences integration test
  tests/integration/features/istio-jwt/istio_jwt.feature
  tests/integration/manifests/istio-jwt-audiences.yaml
Labels: lgtm, area/api-gateway, size/S

#219 Replace usernames with a team name in CODEOWNERS
  CODEOWNERS
Labels: lgtm, area/api-gateway, size/XS

#221 Remove go work in favour of one Go module
  Makefile
  go.mod
  go.sum
  go.work
  go.work.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: lgtm, size/XXL, area/api-gateway

#224 Add missing step for audience integration test
  tests/integration/scenario_audience_test.go
Labels: lgtm, area/api-gateway, size/XS
