Repository kyma-project/api-gateway, pull requests merged in 2023-03, with the labels that each got.

#220 Cluster provisioning scripts for integration tests in api-gateway repo
  tests/integration/README.md
  tests/integration/scripts/README.md
  tests/integration/scripts/gardener/gardener.sh
  tests/integration/scripts/gardener/gcp.sh
  tests/integration/scripts/integration-gardener.sh
  tests/integration/scripts/integration-tests.sh
  tests/integration/scripts/jobguard/run.sh
  tests/integration/scripts/lib/kyma.sh
  tests/integration/scripts/lib/log.sh
  tests/integration/scripts/lib/utils.sh
Labels: size/XL, lgtm, area/api-gateway

#243 Bump dependabot to release 1.4
  .github/dependabot.yml
Labels: lgtm, area/api-gateway, size/XS

#244 Fix jobguard for when waiting on main branch
  tests/integration/scripts/jobguard/run.sh
Labels: lgtm, area/api-gateway, size/XS

#245 Image version format for built image on post-submit
  Makefile
Labels: lgtm, area/api-gateway, size/XS

#247 Fix image version in integration test
  Makefile
Labels: lgtm, area/api-gateway, size/XS

#248 Post image version
  Makefile
Labels: lgtm, area/api-gateway, size/XS

#253 Add documentation about Ory mutators support with Istio
  docs/mutators/id-token-envoyfilter/.helmignore
  docs/mutators/id-token-envoyfilter/Chart.yaml
  docs/mutators/id-token-envoyfilter/files/filter.lua
  docs/mutators/id-token-envoyfilter/templates/06-support-for-mutators.yaml
  docs/mutators/istio-mutators-support.md
Labels: lgtm, area/api-gateway, size/L

#249 add default http timeout value for virtual services
  controllers/api_controller_integration_test.go
  controllers/apirule_controller.go
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/helpers/config.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/types.go
Labels: lgtm, area/api-gateway, size/L

#256 Move performance tests with Ory and Api Gateway to Api Gateway
  Makefile
  performance_tests/Readme.md
  performance_tests/grafana_dashboard.json
  performance_tests/k6_deploy.yaml
  performance_tests/load-testing/.gitignore
  performance_tests/load-testing/.helmignore
  performance_tests/load-testing/Chart.lock
  performance_tests/load-testing/Chart.yaml
  performance_tests/load-testing/templates/_helpers.tpl
  performance_tests/load-testing/templates/apirule-allow.yaml
  performance_tests/load-testing/templates/apirule-grafana.yaml
  performance_tests/load-testing/templates/apirule-jwt-istio.yaml
  performance_tests/load-testing/templates/apirule-noop.yaml
  performance_tests/load-testing/templates/apirule-oauth2.yaml
  performance_tests/load-testing/templates/config-map.yaml
  performance_tests/load-testing/templates/function.yaml
  performance_tests/load-testing/templates/grafana-dashboard.yaml
  performance_tests/load-testing/templates/grafana-datasource.yaml
  performance_tests/load-testing/templates/k6.yaml
  performance_tests/load-testing/templates/oath2client.yaml
  performance_tests/load-testing/values.yaml
  performance_tests/payload-direct.json
  performance_tests/scripts/common.js
  performance_tests/scripts/jwt-post-test.js
  performance_tests/scripts/oauth-post-test.js
  performance_tests/scripts/vars.js
  performance_tests/test.sh
Labels: lgtm, size/XXL, area/api-gateway

#258 Update GO to 1.20.2
  Dockerfile
  go.mod
Labels: lgtm, area/api-gateway, size/XS

#267 Update GO to 1.20.2 (#258)
  Dockerfile
  go.mod
Labels: lgtm, area/api-gateway, size/XS

#269 Add mutators for Istio JWT access strategy
  api/v1beta1/mutators.go
  api/v1beta1/rule.go
  api/v1beta1/zz_generated.deepcopy.go
  config/samples/istio_v1beta1_apirule.yaml
  controllers/api_controller_integration_test.go
  controllers/apirule_controller_status_integration_test.go
  controllers/apirule_controller_validation_integration_test.go
  docs/istio-jwt.md
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/jwt_validator_test.go
  internal/processing/istio/mutators_validator.go
  internal/processing/istio/mutators_validator_test.go
  internal/processing/istio/reconciliation.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/processors/virtual_service_processor.go
  internal/processing/processors/virtual_service_processor_test.go
  internal/validation/validate.go
  tests/integration/features/istio-jwt/istio_jwt_mutators.feature
  tests/integration/istio_jwt_test.go
  tests/integration/main_test.go
  tests/integration/manifests/istio-jwt-multiple-mutators.yaml
  tests/integration/manifests/istio-jwt-mutator-cookie.yaml
  tests/integration/manifests/istio-jwt-mutator-header.yaml
  tests/integration/manifests/istio-jwt-mutators-overwrite.yaml
  tests/integration/pkg/helpers/helpers.go
  tests/integration/pkg/helpers/response_validation.go
  tests/integration/scenario_common_jwt_test.go
  tests/integration/scenario_jwt_multiple_mutators_test.go
  tests/integration/scenario_jwt_mutator_cookie_test.go
  tests/integration/scenario_jwt_mutator_header_test.go
  tests/integration/scenario_jwt_mutators_overwrite_test.go
  tests/integration/scripts/integration-gardener.sh
  tests/integration/test_report.go
Labels: lgtm, size/XXL, area/api-gateway

#277 Code coverage guard
  tests/integration/scripts/code-coverage-guard.sh
Labels: lgtm, size/M, area/api-gateway

#275 Fix changing JWT handler with config map
  controllers/api_controller_integration_test.go
  controllers/apirule_controller.go
  controllers/apirule_controller_status_integration_test.go
  controllers/apirule_controller_validation_integration_test.go
  controllers/reconciliation_test/api_controller_integration_test.go
  controllers/reconciliation_test/suite_test.go
  controllers/suite_test.go
  internal/processing/processors/authorization_policy_processor.go
Labels: lgtm, size/XXL, area/api-gateway
