Repository kyma-project/api-gateway, pull requests merged in 2023-07, with the labels that each got.

#413 Refactor manifests gathering
  tests/integration/pkg/manifestprocessor/processor.go
Labels: lgtm, size/M, area/api-gateway

#416 Fix yaml for resources
  tests/integration/testsuites/custom-domain/manifests/resources.yaml
Labels: lgtm, area/api-gateway, size/XS

#428 Update release-branch in dependabot
  .github/dependabot.yml
Labels: lgtm, area/api-gateway, size/XS

#418 Remove validation step for HTTPS JWT URLs, allowing HTTP URLs as well
  config/crd/apirules.gateway.crd.yaml
  controllers/apirule_controller_validation_integration_test.go
  docs/api-rule-cr.md
  docs/jwt-ory-to-istio.md
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
  internal/processing/ory/jwt_validator.go
  internal/processing/ory/jwt_validator_test.go
  internal/validation/helpers.go
Labels: lgtm, area/api-gateway, size/L
