Repository kyma-project/api-gateway, pull requests merged in 2024-05, with the labels that each got.

#1019 Allow valid values for Istio JWT issuer
  controllers/gateway/apirule_controller_validation_integration_test.go
  docs/user/custom-resources/apirule/04-20-apirule-istio-jwt-access-strategy.md
  internal/processing/istio/jwt_validator.go
  internal/processing/istio/jwt_validator_test.go
Labels: lgtm, size/L, cla: yes

#1032 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1041 Update action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
Labels: lgtm, size/XS, cla: yes

#1043 Adjust workflow to run proper action
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1037 Deprecate kyma provision k3d command
  docs/contributor/01-00-installation.md
  tests/ui/tests/scripts/k3d-local-dev.sh
Labels: lgtm, size/XS, cla: yes

#1048 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1052 Revert "Bump golangci/golangci-lint-action from 4.0.0 to 5.1.0 (#1035)"
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS, cla: yes

#1059 Dependabot for release 2.4
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1061 Fix a link in a sidebar
  docs/user/_sidebar.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
Labels: lgtm, size/XS, cla: yes

#1057 Release API Gateway 2.4.0
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1053 Switch Oathkeeper to CPU only based scaling
  docs/release-notes/2.4.0.md
  docs/user/technical-reference/05-50-ory-limitations.md
  internal/reconciliations/oathkeeper/hpa.yaml
Labels: lgtm, size/S, cla: yes

#1058 Add test for certificate that will expire in one week
  internal/reconciliations/gateway/certificate_test.go
Labels: lgtm, size/M, cla: yes

#1066 Unify CR description in Kyma dashboard
  config/ui-extensions/apigateways/general
Labels: documentation, lgtm, size/XS, cla: yes

#1067 Fail certificate expire test one month before actual cert expiration
  internal/reconciliations/gateway/certificate_test.go
Labels: lgtm, size/S, cla: yes

#1065 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1068 Allow only one hosts for APIRule v1beta2
  apis/gateway/v1beta2/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
Labels: lgtm, size/M, cla: yes

#1076 Fix an issue in the UI tests
  tests/ui/tests/cypress.config.ts
  tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
  tests/ui/tests/support/input.ts
Labels: lgtm, size/S, cla: yes

#1072 Remove apirule v1beta2 subresource statuses
  apis/gateway/v1beta2/apirule_conversion.go
  apis/gateway/v1beta2/apirule_conversion_test.go
  apis/gateway/v1beta2/apirule_types.go
  apis/gateway/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, size/L, cla: yes

#1075 Add troubleshooting guide for conversion webhook certificate secret
  docs/user/troubleshooting-guides/03-60-apirule-conversion-webhook-cert-issue.md
Labels: lgtm, size/S, cla: yes

#1079 Adjust the "get apirule" kubectl command
  docs/user/troubleshooting-guides/03-40-api-rule-troubleshooting.md
Labels: lgtm, size/XS, cla: yes

#1064 Fix v1beta2 conversion for when ory jwt is using in v1beta1
  apis/gateway/v1beta2/apirule_conversion.go
  apis/gateway/v1beta2/apirule_conversion_test.go
  internal/types/ory/jwt.go
Labels: lgtm, size/L, cla: yes

#1069 Fix rendering issue for multiple APIRules
  config/ui-extensions/apirules/dataSources
  config/ui-extensions/apirules/list
  docs/release-notes/2.4.0.md
  tests/ui/tests/cypress.config.ts
  tests/ui/tests/support/commands.ts
  tests/ui/tests/support/list.ts
  tests/ui/tests/tests/api-rule.spec.ts
Labels: kind/bug, lgtm, size/M, cla: yes

#1060 Deprecate kyma provision gardener
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
  tests/integration/scripts/provision-gardener-gh.sh
  tests/integration/scripts/shoot_aws.yaml
  tests/integration/scripts/shoot_gcp.yaml
Labels: lgtm, size/L, cla: yes

#1074 Use MaxAge as an integer value instead of metav1.Duration
  apis/gateway/v1beta2/apirule_conversion.go
  apis/gateway/v1beta2/apirule_conversion_test.go
  apis/gateway/v1beta2/apirule_types.go
  apis/gateway/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  docs/user/custom-resources/apirule/04-60-apirule-v1beta2-custom-resource.md
Labels: lgtm, size/L, cla: yes

#1086 Update sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1087 Run tests on gardener live
  hack/ci/gardener_kubeconfig.sh
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
Labels: lgtm, size/S, cla: yes

#1091 Fix typo
  hack/ci/gardener_kubeconfig.sh
Labels: lgtm, size/XS, cla: yes

#1090 Revert separate variable for Gardener live
  .github/actions/integration-test-gardener/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  hack/ci/gardener_kubeconfig.sh
Labels: lgtm, size/S, cla: yes
