Repository kyma-project/api-gateway, pull requests merged in 2024-03, with the labels that each got.

#914 Define gardenlinux image
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
  tests/integration/scripts/provision-gardener-gh.sh
Labels: lgtm, size/XS, cla: yes

#904 Disable Link Check for a Cloud Flare link
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
Labels: lgtm, size/XS, cla: yes

#916 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#917 Fix gardenlinux image version
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
Labels: lgtm, size/XS, cla: yes

#915 Validate secure and unsecure access strategies
  controllers/gateway/apirule_controller_validation_integration_test.go
  docs/release-notes/2.3.0.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  internal/processing/istio/as_validator.go
  internal/processing/istio/as_validator_test.go
  internal/processing/ory/as_validator.go
  internal/processing/ory/as_validator_test.go
  internal/validation/access_strategy.go
  internal/validation/access_strategy_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  tests/integration/testsuites/istio-jwt/scenario.go
Labels: lgtm, size/L, cla: yes

#924 Fix rendering issue in UI tests
  .github/actions/integration-test-gardener/action.yaml
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/dependabot.yml
  .github/workflows/pull-request.yaml
  .github/workflows/ui-tests.yaml
  tests/ui/tests/package.json
Labels: lgtm, size/M, cla: yes

#927 Define gardenlinux image
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
  tests/integration/scripts/provision-gardener-gh.sh
Labels: lgtm, size/XS, cla: yes

#921 feat: add conditions to gateway cr
  apis/operator/v1alpha1/apigateway_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/crd/bases/operator.kyma-project.io_apigateways.yaml
  config/ui-extensions/apigateways/details
  controllers/gateway/apirule_controller.go
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_controller_test.go
  controllers/status.go
  controllers/status_test.go
  docs/release-notes/2.3.0.md
  docs/user/00-10-overview-api-gateway-controller.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/conditions/suite_test.go
  internal/reconciliations/gateway/gateway.go
  internal/reconciliations/gateway/gateway_test.go
  internal/reconciliations/oathkeeper/oathkeeper.go
  internal/reconciliations/oathkeeper/oathkeeper_test.go
Labels: kind/feature, size/XL, lgtm, area/api-gateway, cla: yes

#934 Wait for cluster role and service account before deploying oathkeeper
  internal/reconciliations/oathkeeper/maester/cluster_role_binding.go
  internal/reconciliations/oathkeeper/maester/service_account.go
Labels: lgtm, size/M, cla: yes

#937 Remove tabs from APIGateway CR UI
  config/ui-extensions/apigateways/details
Labels: lgtm, size/S, cla: yes

#936 bug: fix incorrect conditions names and strings
  internal/conditions/conditions.go
  internal/reconciliations/gateway/gateway_test.go
Labels: kind/bug, lgtm, area/api-gateway, size/S, cla: yes

#935 Reduce UI test flakiness
  tests/ui/tests/config.js
  tests/ui/tests/cypress.config.ts
  tests/ui/tests/fixtures/apiRule.yaml
  tests/ui/tests/fixtures/namespace.yaml
  tests/ui/tests/fixtures/service.yaml
  tests/ui/tests/package-lock.json
  tests/ui/tests/package.json
  tests/ui/tests/plugins/index.ts
  tests/ui/tests/support/apirule.ts
  tests/ui/tests/support/buttons.js
  tests/ui/tests/support/buttons.ts
  tests/ui/tests/support/combobox.js
  tests/ui/tests/support/combobox.ts
  tests/ui/tests/support/commands.ts
  tests/ui/tests/support/dashboard/config.ts
  tests/ui/tests/support/dashboard/index.ts
  tests/ui/tests/support/exceptions.js
  tests/ui/tests/support/exceptions.ts
  tests/ui/tests/support/filter.js
  tests/ui/tests/support/index.js
  tests/ui/tests/support/index.ts
  tests/ui/tests/support/input.ts
  tests/ui/tests/support/k8sclient/apiRule.ts
  tests/ui/tests/support/k8sclient/commands.ts
  tests/ui/tests/support/k8sclient/httpClient.ts
  tests/ui/tests/support/k8sclient/index.ts
  tests/ui/tests/support/k8sclient/kubeconfig.ts
  tests/ui/tests/support/k8sclient/loadFile.ts
  tests/ui/tests/support/k8sclient/namespace.ts
  tests/ui/tests/support/k8sclient/service.ts
  tests/ui/tests/support/list.js
  tests/ui/tests/support/list.ts
  tests/ui/tests/support/loadFile.js
  tests/ui/tests/support/login.js
  tests/ui/tests/support/login.ts
  tests/ui/tests/support/navigation.js
  tests/ui/tests/support/navigation.ts
  tests/ui/tests/support/random.ts
  tests/ui/tests/support/status.ts
  tests/ui/tests/support/views/index.js
  tests/ui/tests/support/views/namespace.js
  tests/ui/tests/support/views/service.js
  tests/ui/tests/tests/api-rule.spec.ts
  tests/ui/tests/tests/api-rule/test-api-rules.spec.js
  tests/ui/tests/tsconfig.json
Labels: lgtm, size/XXL, cla: yes

#941 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#933 Update ci-cd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#942 Remove OIDC login from UI tests
  tests/ui/tests/README.md
  tests/ui/tests/support/login.ts
Labels: lgtm, size/L, cla: yes

#943 Trigger release pipelines
  main.go
Labels: lgtm, size/XS, cla: yes

#944 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#946 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#947 Update dependabot config and add workflow
  .github/dependabot.yml
  .github/workflows/verify-commit-pins.yaml
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#950 go 1.22
  Dockerfile
  Makefile
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  config/crd/bases/operator.kyma-project.io_apigateways.yaml
  config/rbac/role.yaml
  go.mod
Labels: lgtm, size/L, cla: yes

#959 Update managers metrics address
  config/manager/manager.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#960 Add 2.3.1 release notes
  docs/release-notes/2.3.1.md
Labels: lgtm, size/XS, cla: yes

#958 Update managers metrics address
  config/manager/manager.yaml
  docs/release-notes/2.2.2.md
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#962 Add release notes for 2.2.2 and 2.3.1
  docs/release-notes/2.2.2.md
  docs/release-notes/2.3.1.md
Labels: lgtm, size/XS, cla: yes

#964 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#956 bug: ignore NoKindMatch error in oathkeeper reconciliation
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_test.go
Labels: kind/bug, lgtm, size/M, area/api-gateway, cla: yes
