Repository kyma-project/api-gateway, pull requests merged in 2024-10, with the labels that each got.

#1309 Geoblocking ADR draft
  docs/assets/geoblocking-SAP-service.drawio.svg
  docs/assets/geoblocking-cr-controller.drawio.svg
  docs/assets/geoblocking-custom-list.drawio.svg
  docs/assets/geoblocking-namespaces.drawio.svg
  docs/assets/geoblocking.drawio
  docs/assets/geoblocking.svg
  docs/contributor/adr/0010-geoblocking.md
Labels: lgtm, size/L, cla: yes

#1338 Fix periodic UI tests using old version
  .github/actions/get-latest-sha/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/ui-tests-periodic.yaml
  docs/contributor/04-30-ci-cd.md
  scripts/get_latest_build_sha.sh
Labels: lgtm, size/L, cla: yes

#1339 Update CI/CD docs with links
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1340 Add release notes for APIGateway 2.7
  docs/release-notes/2.7.0.md
  docs/user/_sidebar.md
Labels: lgtm, size/S, cla: yes

#1342 Release 2.7.0
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1344 Update dependabot.yml (release-2.7 branch)
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1343 Geoblocking ADR - fixed missing image
  docs/assets/geoblocking.drawio
  docs/assets/geoblocking.drawio.svg
Labels: lgtm, size/M, cla: yes

#1351 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1352 Ignore GitHub Actions patches
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1341 feat: change logic of handling Gardener cluster
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller.go
  controllers/operator/suite_test.go
  hack/crds/gardener/cert.gardener.cloud_certificate.yaml
  hack/crds/gardener/dns.gardener.cloud_dnsentry.yaml
  hack/crds/networking.istio.io_gateways.yaml
  hack/crds/networking.istio.io_virtualservice.yaml
  hack/crds/oathkeeper.ory.sh_rules.yaml
  hack/crds/security.istio.io_authorizationpolicy.yaml
  hack/crds/security.istio.io_peerauthentication.yaml
  hack/crds/security.istio.io_requestauthentication.yaml
  internal/dependencies/dependencies.go
  internal/dependencies/dependencies_test.go
  internal/reconciliations/gardener.go
  internal/reconciliations/gardener_test.go
  internal/reconciliations/gateway/gateway.go
  internal/reconciliations/gateway/gateway_test.go
  internal/reconciliations/gateway/suite_test.go
  internal/reconciliations/oathkeeper/configmap_config.go
  internal/reconciliations/oathkeeper/oathkeeper_test.go
Labels: kind/feature, lgtm, area/api-gateway, size/L, cla: yes

#1357 Extend certificate key size of kyma-gateway to 4096
  docs/release-notes/2.8.0.md
  internal/reconciliations/gateway/certificate.yaml
Labels: lgtm, size/XS, cla: yes

#1361 bug: enable HA control plane nodes
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1360 docs: release notes for Remove hard dependency to Gardener DNSEntry and Certificate resources
  docs/release-notes/2.8.0.md
Labels: lgtm, area/documentation, size/XS, kind/chore, cla: yes

#1358 OAuth2 introspection to extAuth migration tests
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  Makefile
  tests/integration/pkg/hooks/ext-auth.go
  tests/integration/pkg/hooks/istio.go
  tests/integration/pkg/hooks/manifests/ext-auth-istio-cr.yaml
  tests/integration/pkg/hooks/manifests/ext-auth.yaml
  tests/integration/scripts/test-zero-downtime.sh
  tests/integration/testsuites/ory/features/v2alpha1_conversion.feature
  tests/integration/testsuites/ory/manifests/migration-oauth2-introspection-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-oauth2-introspection-v2alpha1.yaml
  tests/integration/testsuites/ory/scenario_migration_oauth2_introspection_v1beta1.go
  tests/integration/testsuites/ory/testsuite.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: lgtm, size/L, cla: yes

#1370 Remove test because it was added just for sane-keeping
  tests/integration/testsuites/upgrade/features/upgrade.feature
  tests/integration/testsuites/upgrade/manifests/upgrade-test-operator-fail.yaml
  tests/integration/testsuites/upgrade/scenario.go
Labels: lgtm, size/L, cla: yes

#1371 remove postman instructions
  docs/user/_sidebar.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-43-expose-workload-short-host-name.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-51-get-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-53-expose-and-secure-workload-istio.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
Labels: lgtm, size/L, cla: yes

#1380 Security scanner config update
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1376 Fix FQDN validation, allowing 1 char labels and 2 chars top level domain
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_controller.go
  internal/helpers/hosts.go
  internal/helpers/hosts_test.go
Labels: lgtm, size/M, cla: yes

#1384 Update tutorial
  docs/user/_sidebar.md
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
Labels: lgtm, size/XS, cla: yes

#1375 fix: Check for Gateway existence after requesting v2alpha1 APIRule
  controllers/gateway/apirule_controller.go
  controllers/gateway/discover_gateway_test.go
  tests/integration/pkg/helpers/api_rule.go
Labels: lgtm, size/L, cla: yes

#1386 Fix link in security
  docs/user/tutorials/01-60-security/01-62-set-up-idp.md
Labels: lgtm, size/XS, cla: yes

#1387 Add new workflow for image syncer
  .github/workflows/main-integration.yaml
  .github/workflows/pull-build-push.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/sync-external-images.yaml
  docs/contributor/04-30-ci-cd.md
  external-images.yaml
Labels: lgtm, size/M, cla: yes

#1388 Add link for sync-external-images to CI/CD docs
  docs/contributor/04-30-ci-cd.md
  external-images.yaml
Labels: size/XS, cla: yes

#1389 chore: merge gitleaks job into pull-request.yaml
  .github/workflows/pull-gitleaks.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1390 docs: update ci/cd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, area/documentation, size/XS, kind/chore, cla: yes

#1381 Fix ApplyApiRule func to respect version of APIRule
  .github/actions/integration-tests/action.yaml
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/ory/manifests/service-per-path.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_validation_error.go
Labels: lgtm, size/L, cla: yes

#1391 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#1374 APIRule v2alpha1 UI
  config/ui-extensions/apirules-v2alpha1/dataSources
  config/ui-extensions/apirules-v2alpha1/details
  config/ui-extensions/apirules-v2alpha1/form
  config/ui-extensions/apirules-v2alpha1/general
  config/ui-extensions/apirules-v2alpha1/kustomization.yaml
  config/ui-extensions/apirules-v2alpha1/list
  config/ui-extensions/apirules-v2alpha1/presets
  config/ui-extensions/apirules-v2alpha1/translations
  config/ui-extensions/apirules/general
  config/ui-extensions/kustomization.yaml
  docs/release-notes/2.8.0.md
  tests/ui/tests/fixtures/apiRuleV2alpha1.yaml
  tests/ui/tests/package.json
  tests/ui/tests/support/k8sclient/apiRule.ts
  tests/ui/tests/support/k8sclient/commands.ts
  tests/ui/tests/support/navigation.ts
  tests/ui/tests/tests/api-rule-v2alpha1.spec.ts
Labels: size/XL, lgtm, cla: yes

#1385 feat: add envoyfilter and ratelimit builders
  internal/builders/envoyfilter/envoyfilter.go
  internal/builders/envoyfilter/envoyfilter_test.go
  internal/ratelimit/ratelimit.go
  internal/ratelimit/ratelimit_test.go
  internal/ratelimit/testdata/envoy_patches.yaml
Labels: kind/feature, size/XL, lgtm, area/api-gateway, cla: yes

#1398 Add required flag for access strategy in APIRule v2alpha1 form
  config/ui-extensions/apirules-v2alpha1/form
Labels: lgtm, size/XS, cla: yes

#1399 Add zero downtime migration test to Slack notification
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1400 RN for fix in APIRule v2alpha1 hosts validation
  docs/release-notes/2.8.0.md
Labels: lgtm, size/XS, cla: yes

#1402 Bump VERSION and sec-scanners-config
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1404 Update dependabot.yml for release-2.8
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1409 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1410 Reduce int tests flakiness
  tests/integration/pkg/hooks/ext-auth.go
Labels: lgtm, size/XS, cla: yes

#1417 Fix links to Istio documentation
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-42-expose-workloads-multiple-namespaces.md
Labels: lgtm, size/S, cla: yes
