Repository kyma-project/api-gateway, pull requests merged in 2024-04, with the labels that each got.

#971 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#978 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#983 Bump golang in cicd test jobs
  .github/actions/integration-test-gardener/action.yaml
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
Labels: lgtm, size/XS, cla: yes

#987 Update istio_jwt.feature
  tests/integration/testsuites/istio-jwt/features/istio_jwt.feature
Labels: lgtm, size/XS, cla: yes

#981 Fix wrong host in busola UI
  config/ui-extensions/apirules/details
  config/ui-extensions/apirules/form
  config/ui-extensions/apirules/list
  config/ui-extensions/apirules/presets
  config/ui-extensions/apirules/translations
  tests/ui/tests/fixtures/apiRule.yaml
  tests/ui/tests/package.json
  tests/ui/tests/support/apirule.ts
  tests/ui/tests/support/buttons.ts
  tests/ui/tests/support/commands.ts
  tests/ui/tests/support/list.ts
  tests/ui/tests/tests/api-rule.spec.ts
Labels: lgtm, size/L, cla: yes

#969 Add UI instructions to API Gateway tutorials
  docs/user/tutorials/01-00-create-workload.md
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  docs/user/tutorials/01-20-set-up-tls-gateway.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-51-get-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-53-expose-and-secure-workload-istio.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
  docs/user/tutorials/01-60-security/01-61-mtls-selfsign-client-certicate.md
  docs/user/tutorials/01-60-security/01-62-set-up-idp.md
Labels: lgtm, size/XXL, cla: yes

#991 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#992 chore: add gitleaks to repo
  .github/workflows/pull-gitleaks.yaml
  .gitleaks.toml
Labels: lgtm, area/ci, size/XXL, kind/chore, cla: yes

#997 docs: add gitleaks docu
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1001 chore: Update maxAge documentation and placeholder
  config/ui-extensions/apirules/form
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
Labels: lgtm, size/M, cla: yes

#1005 Add a directory with ADRs
  .github/ISSUE_TEMPLATE/adr.md
  docs/contributor/adr/0000-supported-api-gateway-configurations.md
  docs/contributor/adr/0001-istio-jwt-proposal.md
  docs/contributor/adr/0002-module-operator-design.md
  docs/contributor/adr/0003-cors-headers-configuration-for-apirules-v1.md
  docs/contributor/adr/0004-api-gateway-cr-status-improvements.md
  docs/contributor/adr/0005-api-proposal-for-configuration-of-external-authorizer-based-authorization-in-apirules.md
  docs/contributor/adr/0006-support-setting-up-custom-headers-in-apirule.md
  docs/contributor/adr/0007-apirule-v1beta2-api-proposal.md
  docs/contributor/adr/adr-template.md
Labels: size/XL, lgtm, cla: yes

#1008 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1012 Fix link in the adr folder
  docs/contributor/adr/0004-api-gateway-cr-status-improvements.md
Labels: lgtm, size/XS, cla: yes

#1017 Update documentation about installing api-gateway on K3D
  README.md
  docs/contributor/01-00-installation.md
Labels: lgtm, size/S, cla: yes

#1021 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1022 Priority class name for api-gateway
  config/manager/manager.yaml
Labels: lgtm, size/XS, cla: yes

#1020 Remove no longer existing jobs from cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1018 Run ui tests on schedule
  .github/workflows/ui-tests-periodic.yaml
  .github/workflows/ui-tests.yaml
  docs/contributor/04-30-ci-cd.md
  tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
Labels: lgtm, size/L, cla: yes
