Repository kyma-project/api-gateway, pull requests merged in 2024-12, with the labels that each got.

#1490 Log errorMap before updateStatus fails
  internal/processing/reconciliation.go
Labels: lgtm, size/S, cla: yes

#1503 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1496 Faster requeue when object has been modified error happens
  controllers/gateway/apirule_controller.go
  controllers/gateway/suite_test.go
  controllers/gateway/types.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  main.go
Labels: lgtm, size/M, cla: yes

#1507 QOL updates to APIRule v2alpha1 integration tests
  tests/integration/main_test.go
  tests/integration/pkg/helpers/string.go
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/testsuites/v2alpha1/features/asterisk.feature
  tests/integration/testsuites/v2alpha1/features/cors.feature
  tests/integration/testsuites/v2alpha1/features/expose_methods_on_paths.feature
  tests/integration/testsuites/v2alpha1/features/ext_auth.feature
  tests/integration/testsuites/v2alpha1/features/jwt.feature
  tests/integration/testsuites/v2alpha1/features/no_auth.feature
  tests/integration/testsuites/v2alpha1/features/request.feature
  tests/integration/testsuites/v2alpha1/features/service.feature
  tests/integration/testsuites/v2alpha1/features/short_host.feature
  tests/integration/testsuites/v2alpha1/features/validation.feature
  tests/integration/testsuites/v2alpha1/manifests/global-commons.yaml
  tests/integration/testsuites/v2alpha1/manifests/second-service.yaml
  tests/integration/testsuites/v2alpha1/manifests/testing-app.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_asterisk.go
  tests/integration/testsuites/v2alpha1/scenario_cors_custom.go
  tests/integration/testsuites/v2alpha1/scenario_cors_default.go
  tests/integration/testsuites/v2alpha1/scenario_ext_auth.go
  tests/integration/testsuites/v2alpha1/scenario_initializers.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_and_unrestricted.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_audience.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_common.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_issuer_jwks_not_match.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_scopes.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_header.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_param.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_unavailable_issuer.go
  tests/integration/testsuites/v2alpha1/scenario_no_auth.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_jwt.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_noauth.go
  tests/integration/testsuites/v2alpha1/scenario_request_modification.go
  tests/integration/testsuites/v2alpha1/scenario_service_custom_label_selector.go
  tests/integration/testsuites/v2alpha1/scenario_service_diff_same_methods.go
  tests/integration/testsuites/v2alpha1/scenario_service_fallback.go
  tests/integration/testsuites/v2alpha1/scenario_service_two_namespaces.go
  tests/integration/testsuites/v2alpha1/scenario_short_host.go
  tests/integration/testsuites/v2alpha1/scenario_validation_error.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#1519 Use static kubeconfig name in github actions
  .github/actions/integration-test-gardener/action.yaml
  hack/ci/custom-domain-gardener.sh
Labels: lgtm, size/S, cla: yes

#1521 Only use scenario initializer for v2alpha1 tests
  tests/integration/main_test.go
Labels: lgtm, size/S, cla: yes

#1526 bug: change ORY PodDisruptionBudget
  internal/reconciliations/oathkeeper/pod_disruption_budget.yaml
Labels: kind/bug, lgtm, area/api-gateway, size/XS, cla: yes

#1508 Ratelimit validation
  PROJECT
  apis/gateway/ratelimit/v1alpha1/groupversion_info.go
  apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
  apis/gateway/ratelimit/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
  config/crd/bases/ratelimit.kyma-project.io_ratelimits.yaml
  config/crd/kustomization.yaml
  config/dev/kustomization.yaml
  config/prod/kustomization.yaml
  config/samples/gateway_v1alpha1_ratelimit.yaml
  controllers/gateway/ratelimit/ratelimit_controller.go
  controllers/gateway/ratelimit/ratelimit_controller_test.go
  controllers/gateway/ratelimit/ratelimit_disabled.go
  controllers/gateway/ratelimit/ratelimit_enabled.go
  controllers/gateway/suite_test.go
  controllers/ratelimit/ratelimit_controller_test.go
  controllers/ratelimit/suite_test.go
  docs/assets/operator-contributor-skr-overview.svg
  docs/assets/operator-overview.svg
  docs/contributor/04-10-technical-design.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  docs/user/custom-resources/ratelimit/04-00-ratelimit.md
  internal/ratelimit/validate.go
  internal/ratelimit/validate_test.go
  main.go
Labels: size/XL, lgtm, cla: yes

#1528 Add issuerRef to kyma-tls-cert certificate
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  internal/reconciliations/gateway/certificate.yaml
  tests/integration/testsuites/custom-domain/manifests/resources.yaml
Labels: lgtm, size/XS, cla: yes

#1531 docs: update 04-30-ci-cd.md with new links to files
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, area/documentation, area/ci, kind/chore, cla: yes

#1529 Add issuerRef to kyma-tls-cert certificate
  docs/release-notes/2.10.1.md
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  internal/reconciliations/gateway/certificate.yaml
  tests/integration/testsuites/custom-domain/manifests/resources.yaml
Labels: lgtm, size/XS, cla: yes

#1532 Release 2.10.1
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1536 Copy logs before Gardener deprovision
  .github/actions/integration-test-gardener/action.yaml
  .github/workflows/call-integration-release.yaml
  .github/workflows/post-main-integration.yaml
  hack/ci/custom-domain-gardener-aws.sh
  hack/ci/custom-domain-gardener-gcp.sh
  hack/ci/custom-domain-gardener.sh
  hack/ci/deprovision-gardener.sh
  hack/ci/provision-gardener.sh
  hack/ci/set-aws-gardener.sh
  hack/ci/set-gcp-gardener.sh
  tests/integration/pkg/auth/auth.go
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/ory/scenario_oauth2_jwt_one_path.go
Labels: lgtm, size/L, cla: yes

#1537 Adjust gh actions post workflow
  .github/actions/e2e-test-gardener/action.yaml
  .github/actions/e2e-test-k3d/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/slack-notification-failed-workflow/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/call-integration-release.yaml
  .github/workflows/call-pull-integration.yaml
  .github/workflows/call-unit-lint.yaml
  .github/workflows/post-main-integration.yaml
  Makefile
  hack/ci/integration-test-gardener.sh
  hack/ci/set-aws-gardener.sh
  hack/ci/set-gcp-gardener.sh
  tests/integration/env_vars.sh
  tests/integration/env_vars_custom_domain.sh
  tests/integration/pkg/testcontext/testsuite.go
  tests/integration/scripts/test-zero-downtime.sh
  tests/integration/testsuites/gateway/testsuite.go
Labels: lgtm, size/L, cla: yes

#1548 Fix trailing comma in slack notification action
  .github/actions/slack-notification-failed-workflow/action.yaml
Labels: lgtm, size/XS, cla: yes

#1547 Bump Kubernetes version for e2e tests
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  hack/ci/set-aws-gardener.sh
  hack/ci/set-gcp-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1523 Testing strategy for APIGateway module
  docs/contributor/02-10-testing-strategy.md
Labels: size/M, cla: yes

#1549 Update CICD docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/S, cla: yes

#1541 Add quick start guide and new README
  docs/assets/operator-overview-with-rate-limit.svg
  docs/assets/operator-overview.svg
  docs/user/00-10-overview-api-gateway-controller.md
  docs/user/00-20-overview-api-rule-controller.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/os-quick-start.md
  docs/user/technical-reference/05-50-ory-limitations.md
Labels: lgtm, size/L, cla: yes

#1551 Fix slack notification action and adjust post workflow name
  .github/actions/slack-notification-failed-workflow/action.yaml
  .github/workflows/post-main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1543 feat: RateLimit CR reconciliation
  Makefile
  apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
  apis/gateway/ratelimit/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
  config/samples/gateway_v1alpha1_ratelimit.yaml
  controllers/gateway/ratelimit/ratelimit_controller.go
  controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
  controllers/gateway/ratelimit/ratelimit_controller_test.go
  controllers/gateway/ratelimit/ratelimit_enabled.go
  hack/crds/networking.istio.io_envoyfilters.yaml
  internal/builders/envoyfilter/envoyfilter.go
  internal/ratelimit/ratelimit.go
  internal/ratelimit/ratelimit_test.go
Labels: kind/feature, size/XL, lgtm, area/api-gateway, cla: yes

#1553 Bump slack action for failed workflow notification
  .github/actions/slack-notification-failed-workflow/action.yaml
  .github/workflows/post-main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1563 Fix requeue on error of APIRule
  Dockerfile
  controllers/gateway/apirule_controller.go
  controllers/gateway/reconcile_result.go
Labels: lgtm, size/S, cla: yes

#1562 Fix broken links and move CRs' status descriptions
  README.md
  docs/release-notes/2.2.0.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  docs/user/technical-reference/05-00-api-gateway-operator-parameters.md
Labels: do-not-merge/hold, lgtm, size/M, cla: yes

#1565 Fixed workflow name to get the correct image for tests
  .github/actions/get-latest-sha/action.yaml
Labels: lgtm, size/XS, cla: yes

#1564 Use error requeue on convert and update
  controllers/gateway/apirule_controller.go
Labels: lgtm, size/S, cla: yes

#1558 bug: RateLimit: replace Watch with polling
  apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
  config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
  config/rbac/role.yaml
  controllers/gateway/ratelimit/ratelimit_controller.go
  controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
  controllers/gateway/ratelimit/ratelimit_enabled.go
  internal/dependencies/dependencies.go
Labels: kind/bug, size/M, area/api-gateway, cla: yes

#1572 Add the tutorial on XFF
  docs/user/_sidebar.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-55-ip-based-access-with-xff.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-55-ip-based-access-with-xff.md
Labels: lgtm, size/L, cla: yes

#1571 Adjust pull request cicd workflow to the new strategy
  .github/workflows/call-pull-integration.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/M, cla: yes

#1573 Update cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/S, cla: yes

#1559 Update API Gateway tutorials
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  docs/user/tutorials/01-20-set-up-tls-gateway.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-40-expose-workload/v2alpha1/01-43-expose-workload-short-host-name.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-51-get-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-53-expose-and-secure-workload-istio.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-53-expose-and-secure-workload-ext-auth.md
Labels: size/XL, lgtm, cla: yes
