Repository kyma-project/api-gateway, pull requests merged in 2024-08, with the labels that each got.

#1215 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1210 Extend CEL validation
  Dockerfile
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
  docs/release-notes/2.5.0.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  internal/processing/processors/istio/reconciliation.go
  internal/processing/processors/ory/reconciliation.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/validation/v1beta1/v1beta1.go
  internal/validation/v1beta1/v1beta1_test.go
  internal/validation/v2alpha1/gateway.go
  internal/validation/v2alpha1/gateway_test.go
  internal/validation/v2alpha1/hosts.go
  internal/validation/v2alpha1/hosts_test.go
  internal/validation/v2alpha1/v2alpha1.go
  internal/validation/v2alpha1/v2alpha1_test.go
  internal/validation/validate.go
Labels: size/XL, lgtm, cla: yes

#1217 Change reconciliation time to 30 minutes
  main.go
Labels: lgtm, size/XS, cla: yes

#1223 bug: add retry logic for creating shoot clusters
  tests/integration/scripts/provision-gardener-gh.sh
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#1216 Use URI instead of URL
  controllers/gateway/apirule_controller_validation_integration_test.go
  docs/user/custom-resources/apirule/04-30-apirule-jwt-ory-and-istio-comparison.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v2alpha1/03-40-api-rule-troubleshooting.md
  internal/validation/helpers.go
  internal/validation/v1beta1/istio/jwt_validator.go
  internal/validation/v1beta1/istio/jwt_validator_test.go
  internal/validation/v1beta1/ory/jwt_validator.go
  internal/validation/v1beta1/ory/jwt_validator_test.go
  internal/validation/v2alpha1/jwt.go
Labels: lgtm, size/M, cla: yes

#1207 Support for request modifiers in APIRule v2alpha1
  apis/gateway/v2alpha1/apirule_conversion.go
  apis/gateway/v2alpha1/apirule_conversion_test.go
  apis/gateway/v2alpha1/apirule_types.go
  apis/gateway/v2alpha1/mutators.go
  apis/gateway/v2alpha1/mutators_test.go
  apis/gateway/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  docs/release-notes/2.5.0.md
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  internal/builders/virtual_service.go
  internal/processing/helpers.go
  internal/processing/processors/istio/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/request_test.go
  internal/processing/processors/v2alpha1/virtualservice/test_builders_test.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
  tests/integration/testsuites/v2alpha1/features/request.feature
  tests/integration/testsuites/v2alpha1/manifests/jwt-request-cookie.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-request-header.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_request_modification.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: size/XL, lgtm, cla: yes

#1227 bug: fix premature error of kubectl get --raw /readyz
  tests/integration/scripts/provision-gardener-gh.sh
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1211 v2alpha1 AuthorizationPolicy processor
  apis/gateway/v2alpha1/gateway_suite_test.go
  apis/gateway/v2alpha1/service.go
  apis/gateway/v2alpha1/service_test.go
  apis/gateway/v2alpha1/test_builders_test.go
  internal/builders/istio.go
  internal/processing/helpers.go
  internal/processing/label.go
  internal/processing/label_test.go
  internal/processing/processing_suite_test.go
  internal/processing/processors/authorization_policy_processor.go
  internal/processing/processors/migration/processors.go
  internal/processing/processors/migration/processors_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/suite_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/test_builders_test.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/validation/v2alpha1/sidecar_injection.go
Labels: lgtm, size/XXL, cla: yes

#1225 VERSION file and sec-scanners-config
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1226 Bump dependabot config for 2.5
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1228 V2alpha1 RequestAuthentication processor
  internal/builders/istio.go
  internal/processing/processors/migration/processors.go
  internal/processing/processors/migration/processors_test.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/requestauthentication/creator.go
  internal/processing/processors/v2alpha1/requestauthentication/processing_existing_ra_test.go
  internal/processing/processors/v2alpha1/requestauthentication/processing_new_ra_test.go
  internal/processing/processors/v2alpha1/requestauthentication/processor.go
  internal/processing/processors/v2alpha1/requestauthentication/service_selector_test.go
  internal/processing/processors/v2alpha1/requestauthentication/suite_test.go
  internal/processing/processors/v2alpha1/requestauthentication/test_builders_test.go
Labels: lgtm, size/XXL, cla: yes

#1232 Run integration test suites in a matrix in Pull Request workflow
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/pull-integration.yaml
  Makefile
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1229 Add Httpbin Service and wait for ready to migration tests
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/testsuites/ory/features/v2alpha1_conversion.feature
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_delete_allow_v1beta1.go
  tests/integration/testsuites/ory/scenario_delete_noAuth_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_allow_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noauth_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noop_v1beta1.go
Labels: lgtm, size/S, cla: yes

#1208 chore: cleanup cicd scripts
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-unit-lint.yaml
  hack/ci/code-coverage-guard.sh
  hack/ci/custom-domain-gardener-aws.sh
  hack/ci/custom-domain-gardener-gcp.sh
  hack/ci/custom-domain-gardener.sh
  hack/ci/provision-gardener.sh
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
  tests/integration/scripts/README.md
  tests/integration/scripts/custom-domain-gardener-aws-gh.sh
  tests/integration/scripts/custom-domain-gardener-gcp.sh
  tests/integration/scripts/custom-domain-gardener-gh.sh
  tests/integration/scripts/jobguard.sh
  tests/integration/scripts/provision-gardener.sh
  tests/integration/scripts/test-gardener-aws.sh
  tests/integration/scripts/test-gardener-gcp.sh
  tests/integration/scripts/test-gardener.sh
Labels: lgtm, size/L, cla: yes

#1239 cicd: fix wrong script reference
  hack/ci/custom-domain-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1241 cicd: fix wrong script reference
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1240 ADR for request modifiers
  docs/contributor/adr/0009-request-modifiers.md
Labels: lgtm, size/M, cla: yes

#1243 Update security scanner configuration
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1242 cicd: bump k8s versions for int tests
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/provision-k3d-cluster/action.yaml
  .github/actions/upgrade-test/action.yaml
  hack/ci/custom-domain-gardener-aws.sh
  hack/ci/custom-domain-gardener-gcp.sh
Labels: lgtm, size/M, cla: yes

#1244 Gateway validation error message
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
Labels: lgtm, size/XS, cla: yes

#1255 Fix a broken link
  docs/contributor/adr/0001-istio-jwt-proposal.md
Labels: lgtm, size/XS, cla: yes

#1253 Remove leftover cicd
  .github/actions/upgrade-test/action.yaml
Labels: lgtm, size/XS, cla: yes

#1256 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1252 Split integration tests suite execution on release PRs
  .github/actions/integration-test-gardener/action.yaml
  .github/workflows/pull-integration-release.yaml
  Makefile
  apis/gateway/v1beta1/authorization.go
  apis/gateway/v2alpha1/authorization.go
  docs/contributor/04-30-ci-cd.md
  hack/ci/custom-domain-gardener-aws.sh
  hack/ci/custom-domain-gardener-gcp.sh
  hack/ci/custom-domain-gardener.sh
  tests/integration/test_report.go
  tests/integration/testsuites/upgrade/features/upgrade.feature
  tests/integration/testsuites/upgrade/scenario.go
Labels: lgtm, size/L, cla: yes

#1262 Fix upload logs/artefacts on test-gardener action when using matrix
  .github/actions/integration-test-gardener/action.yaml
Labels: lgtm, size/XS, cla: yes

#1264 Fix gardener provision bash scripts
  hack/ci/custom-domain-gardener.sh
  hack/ci/gardener_kubeconfig.sh
  hack/ci/provision-gardener.sh
Labels: lgtm, size/M, cla: yes

#1268 Update security scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1270 Oathkeeper startup optimisation
  internal/reconciliations/oathkeeper/deployment.go
  internal/reconciliations/oathkeeper/deployment.yaml
  internal/reconciliations/oathkeeper/deployment_light.yaml
Labels: lgtm, size/S, cla: yes

#1263 Better empty spec error message
  internal/validation/v2alpha1/v2alpha1.go
  internal/validation/v2alpha1/v2alpha1_test.go
Labels: lgtm, size/XS, cla: yes
