Repository kyma-project/api-gateway, pull requests merged in 2024-02, with the labels that each got.

#852 Use includeTemplates: true when templating default kustomization.yaml
  .gitignore
  Makefile
  config/crd/kustomization.yaml
  config/default/kustomization.template.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/rbac/kustomization.yaml
  config/scheduling/kustomization.yaml
  config/ui-extensions/apigateways/kustomization.yaml
  config/ui-extensions/apirules/kustomization.yaml
  tests/integration/testsuites/gateway/metadata.go
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/L, cla: yes

#853 Add PodDisruptionBudget for Oathkeeper
  config/rbac/role.yaml
  controllers/operator/apigateway_controller.go
  controllers/operator/suite_test.go
  docs/release-notes/2.2.0.md
  internal/reconciliations/oathkeeper/oathkeeper.go
  internal/reconciliations/oathkeeper/oathkeeper_test.go
  internal/reconciliations/oathkeeper/pod_disruption_budget.go
  internal/reconciliations/oathkeeper/pod_disruption_budget.yaml
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/gateway/features/kyma_gateway.feature
Labels: lgtm, size/L, cla: yes

#855 Update the notes' style
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/custom-resources/apirule/04-20-apirule-istio-jwt-access-strategy.md
  docs/user/custom-resources/apirule/04-30-apirule-jwt-ory-and-istio-comparison.md
  docs/user/custom-resources/apirule/04-50-apirule-authorizations.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-02-404-not-found.md
  docs/user/troubleshooting-guides/03-10-dns-mgt/03-10-dns-mgt-connection-refused.md
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
  docs/user/tutorials/01-60-security/01-61-mtls-selfsign-client-certicate.md
  docs/user/tutorials/01-60-security/01-62-set-up-idp.md
Labels: lgtm, size/L, cla: yes

#856 Update api-gateway-manager version for security scanners
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#865 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#857 Integration tests with OAuth2 mock
  .github/actions/integration-test-gardener/action.yaml
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
  docs/contributor/01-10-API-Gateway-CRD-proposal.md
  docs/contributor/04-30-ci-cd.md
  tests/integration/README.md
  tests/integration/env_vars.sh
  tests/integration/env_vars_custom_domain.sh
  tests/integration/jwt_handler.go
  tests/integration/pkg/auth/auth.go
  tests/integration/pkg/auth/oauth2-server-mock.go
  tests/integration/pkg/auth/oauth2-server-mock.yaml
  tests/integration/pkg/helpers/http_client.go
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/pkg/hooks/dns.go
  tests/integration/pkg/hooks/istio.go
  tests/integration/pkg/hooks/manifests/api-gateway.yaml
  tests/integration/pkg/hooks/manifests/apigateway.yaml
  tests/integration/pkg/istio/istiod.go
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/pkg/network/coredns-custom.yml
  tests/integration/pkg/network/dns.go
  tests/integration/pkg/testcontext/config.go
  tests/integration/testsuites/custom-domain/testsuite.go
  tests/integration/testsuites/gateway/features/deletion.feature
  tests/integration/testsuites/gateway/features/kyma_gateway.feature
  tests/integration/testsuites/gateway/testsuite.go
  tests/integration/testsuites/istio-jwt/features/Istio_jwt_two_strategies.feature
  tests/integration/testsuites/istio-jwt/features/istio_jwt.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-jwt-audiences.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_audience.go
  tests/integration/testsuites/istio-jwt/scenario_oauth_and_jwt.go
  tests/integration/testsuites/istio-jwt/scenario_scopes.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/testsuite.go
  tests/integration/testsuites/upgrade/testsuite.go
Labels: size/XL, lgtm, cla: yes

#869 Remove oathkeeper cronjob deletion reconcile leftovers
  config/rbac/role.yaml
  controllers/operator/apigateway_controller.go
  internal/reconciliations/oathkeeper/cronjob/cronjob.go
  internal/reconciliations/oathkeeper/cronjob/role.go
  internal/reconciliations/oathkeeper/cronjob/role_binding.go
  internal/reconciliations/oathkeeper/cronjob/service_account.go
  internal/reconciliations/oathkeeper/oathkeeper.go
  internal/reconciliations/oathkeeper/oathkeeper_test.go
Labels: lgtm, size/L, cla: yes

#868 Fix APIRule details UI when listing related VSs
  config/ui-extensions/apirules/dataSources
Labels: lgtm, size/XS, cla: yes

#871 Remove outdated handler name and add no_auth instead
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
Labels: lgtm, size/XS, cla: yes

#875 Do not merge manifest when upgrading
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/upgrade/features/upgrade.feature
  tests/integration/testsuites/upgrade/manifests/upgrade-test-operator-fail.yaml
  tests/integration/testsuites/upgrade/scenario.go
Labels: lgtm, size/L, cla: yes

#878 Attach custom domain aws job to the slack notification on main workflow
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#867 Add mTLS guide for istio and api-gateway
  docs/user/tutorials/01-00-create-workload.md
  docs/user/tutorials/01-20-set-up-tls-gateway.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
Labels: kind/feature, lgtm, area/ci, size/L, cla: yes

#882 Use warning instead of error on duplicate APIGateway CRs
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_controller_test.go
  tests/integration/testsuites/gateway/features/kyma_gateway.feature
Labels: lgtm, size/M, cla: yes

#886 Update the docs related to Warning state on duplicate APIGateway CRs
  docs/contributor/04-10-technical-design.md
  docs/release-notes/2.2.0.md
  docs/user/custom-resources/apigateway/04-00-apigateway-custom-resource.md
Labels: lgtm, size/XS, cla: yes

#888 Update manager image in sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#880 Remove `generated-objects-labels` parameter
  controllers/gateway/types.go
  docs/release-notes/2.2.0.md
  docs/user/technical-reference/05-00-api-gateway-operator-parameters.md
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/access_rule_processor.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/request_authentication_processor.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/authorization_policy_processor.go
  internal/processing/ory/request_authentication_processor.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/processing/processors/access_rule_processor.go
  internal/processing/types.go
  main.go
Labels: lgtm, area/ci, kind/cleanup, size/L, cla: yes

#889 chore: bump sec-scanners-config.yaml image to 2.2.0
  sec-scanners-config.yaml
Labels: lgtm, area/api-gateway, size/XS, kind/chore, cla: yes

#890 Update APIRules in tutorials to use the no_auth handler
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
Labels: lgtm, size/XS, cla: yes

#893 Use 'in a cluster' instead of 'on a cluster'
  docs/contributor/01-30-api-rule-dependencies.md
  docs/contributor/04-10-technical-design.md
  docs/release-notes/2.0.0.md
  docs/release-notes/2.2.0.md
  docs/user/custom-resources/apigateway/04-10-kyma-gateway.md
  docs/user/troubleshooting-guides/03-50-certificates-gardener.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
Labels: lgtm, size/S, cla: yes

#891 Custom domain test remove env variables
  tests/integration/env_vars_custom_domain.sh
  tests/integration/pkg/helpers/http_client.go
Labels: lgtm, size/XS, cla: yes

#804 Update RBAC to not use *
  config/rbac/role.yaml
  controllers/operator/apigateway_controller.go
  internal/reconciliations/oathkeeper/maester/cluster_role.yaml
Labels: lgtm, size/S, cla: yes

#895 fix: Update mutators UI to use yaml editors
  config/ui-extensions/apirules/details
  config/ui-extensions/apirules/form
  docs/release-notes/2.3.0.md
  tests/ui/tests/support/exceptions.js
  tests/ui/tests/support/index.js
  tests/ui/tests/support/list.js
  tests/ui/tests/tests/api-rule/test-api-rules.spec.js
Labels: lgtm, size/L, cla: yes

#899 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#896 Use custom or Kyma domain placeholder in the mTLS tutorial
  docs/user/tutorials/01-00-create-workload.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
Labels: lgtm, size/M, cla: yes

#864 Fix annotations from templates
  internal/reconciliations/gateway/dns_entry_test.go
  internal/reconciliations/resource.go
Labels: lgtm, size/XS, cla: yes

#908 Add garden Annotation to DNSEntry
  internal/reconciliations/gateway/dns_entry_test.go
  internal/reconciliations/resource.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, cla: yes

#909 Add 2.2.1 release notes
  docs/release-notes/2.2.1.md
Labels: lgtm, size/XS, cla: yes

#911 Add VERSION
  VERSION
Labels: lgtm, size/XS, cla: yes

#912 Update dependabot.yml for release-2.2 branch
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes
