Repository kyma-project/api-gateway, pull requests merged in 2024-06, with the labels that each got.

#1100 Fix CORS MaxAge default value and conversion
  apis/gateway/v1beta2/apirule_conversion.go
  apis/gateway/v1beta2/apirule_conversion_test.go
  apis/gateway/v1beta2/apirule_types.go
  apis/gateway/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, size/L, cla: yes

#1096 Adjust the troubleshooting section to the new version of ApiRule
  docs/user/_sidebar.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-00-basic-diagnostics.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-40-api-rule-troubleshooting.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/README.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v1beta2/03-00-basic-diagnostics.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v1beta2/03-01-401-unauthorized-403-forbidden.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v1beta2/03-40-api-rule-troubleshooting.md
  docs/user/tutorials/README.md
Labels: lgtm, size/L, cla: yes

#1103 Move APIRule troubleshooting guide
  docs/user/_sidebar.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-40-api-rule-troubleshooting.md
Labels: lgtm, size/XS, cla: yes

#1105 Fix a broken link
  docs/user/_sidebar.md
Labels: lgtm, area/documentation, size/XS, kind/chore, cla: yes

#1101 Switch mock image to networking-dev-tools built
  tests/integration/pkg/auth/oauth2-server-mock.yaml
Labels: lgtm, size/XS, cla: yes

#1110 Add restart hook to verify behaviour wrt Istio test flakiness
  .github/workflows/pull-integration.yaml
  tests/integration/pkg/hooks/verify-controller-restart.go
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/gateway/scenario.go
  tests/integration/testsuites/upgrade/scenario.go
Labels: do-not-merge/hold, size/L, cla: yes

#1114 Add UI instructions to API Gateway tutorials - cherry-pick
  docs/user/tutorials/01-00-create-workload.md
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
  docs/user/tutorials/01-20-set-up-tls-gateway.md
  docs/user/tutorials/01-30-set-up-mtls-gateway.md
  docs/user/tutorials/01-40-expose-workload/01-40-expose-workload-apigateway.md
  docs/user/tutorials/01-40-expose-workload/01-41-expose-multiple-workloads.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-50-expose-and-secure-workload-oauth2.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-51-get-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-52-expose-and-secure-workload-jwt.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-53-expose-and-secure-workload-istio.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-54-expose-and-secure-workload-with-certificate.md
  docs/user/tutorials/01-60-security/01-61-mtls-selfsign-client-certicate.md
  docs/user/tutorials/01-60-security/01-62-set-up-idp.md
Labels: lgtm, size/XXL, cla: yes

#1111 Bump controller-runtime and kubebuilder
  go.mod
  go.sum
Labels: lgtm, size/M, cla: yes

#1117 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1119 refactor: unify workflows into single pipeline
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/pull-unit-lint.yaml
  .github/workflows/ui-tests.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, area/ci, size/L, kind/chore, cla: yes

#1120 refactor: add lint and unit tests
  .github/workflows/pull-request.yaml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1121 Update security scanner image
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1125 docs: fix typo in 01-00-create-workload.md
  docs/user/tutorials/01-00-create-workload.md
Labels: kind/bug, lgtm, area/documentation, size/XS, cla: yes

#1126 APIRule v2alpha1 conversion fix for unconvertible / empty spec cases
  Makefile
  apis/gateway/v2alpha1/apirule_conversion.go
  apis/gateway/v2alpha1/apirule_conversion_test.go
  apis/gateway/v2alpha1/jwt_conversion.go
  controllers/gateway/apirule_controller.go
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  docs/user/custom-resources/apirule/v2alpha1/04-15-api-rule-access-strategies.md
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/ory/features/v2alpha1_conversion.feature
  tests/integration/testsuites/ory/manifests/delete-allow-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/delete-noauth-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-allow-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-allow-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-jwt-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-jwt-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-noauth-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-noauth-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-noop-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-noop-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/v1beta1-noauth-delete.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_delete_allow_v1beta1.go
  tests/integration/testsuites/ory/scenario_delete_noAuth_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_allow_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_jwt_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noauth_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noop_v1beta1.go
  tests/integration/testsuites/ory/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#1122 docs: update cicd documentation
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1129 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1134 PoC for APIRule migration
  apis/gateway/v2alpha1/jwt_conversion.go
  controllers/gateway/apirule_controller.go
  docs/contributor/draft/apirule-migration.md
  internal/processing/istio/reconciliation.go
  internal/processing/migration/access_rule_processor.go
  internal/processing/migration/as_validator.go
  internal/processing/migration/jwt_validator.go
  internal/processing/migration/reconciliation.go
  internal/processing/ory/reconciliation.go
  internal/processing/reconciliation.go
  internal/processing/types.go
  internal/validation/validate.go
Labels: do-not-merge/hold, size/L, cla: yes
