Repository kyma-project/api-gateway, pull requests merged in 2024-01, with the labels that each got.

#793 Fix upgrade test script for release branches
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
Labels: lgtm, size/S, cla: yes

#791 Move custom domain post job to Github Actions
  .github/actions/integration-test-gardener/action.yaml
  .github/workflows/main-integration.yaml
  docs/contributor/04-30-ci-cd.md
  hack/ci/gardener_kubeconfig.sh
  tests/integration/scripts/custom-domain-gardener-gcp-gh.sh
  tests/integration/scripts/custom-domain-gardener-gh.sh
  tests/integration/scripts/provision-gardener-gh.sh
Labels: lgtm, size/L, cla: yes

#794 Fix image repository path in workflow
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#796 Release API Gateway 2.1.0
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#799 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#800 Add request flow for API Gateway
  docs/assets/api-gateway-request-flow.svg
  docs/user/_sidebar.md
  docs/user/technical-reference/05-10-api-gateway-request-flow.md
Labels: lgtm, size/S, cla: yes

#803 Add API-Gateway operator metrics service
  config/manager/kustomization.yaml
  config/manager/metrics_service.yaml
  main.go
Labels: lgtm, size/S, cla: yes

#810 Security scanner config update
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#815 Add missing HTTP methods in APIRule UI
  config/ui-extensions/apirules/form
  docs/release-notes/2.1.1.md
Labels: lgtm, size/S, cla: yes

#822 Cherry Pick: Add missing HTTP methods in APIRule UI (#815)
  config/ui-extensions/apirules/form
  docs/release-notes/2.1.1.md
Labels: lgtm, size/S, cla: yes

#807 Revisit Issue and PR templates
  .github/ISSUE_TEMPLATE/adr.md
  .github/ISSUE_TEMPLATE/deprecation_deletion.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
  .github/pull-request-template.md
Labels: lgtm, size/M, cla: yes

#825 Update release branch in Dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#828 Update api-gateway-manager image for security scanners
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#835 Fix custom-domain integration tests
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/XS, cla: yes

#837 Fix broken links
  docs/contributor/04-30-ci-cd.md
  docs/release-notes/2.1.0.md
  docs/user/tutorials/01-40-expose-workload/01-42-expose-workloads-multiple-namespaces.md
Labels: lgtm, size/S, cla: yes

#830 Revert allow
  apis/gateway/v1beta1/apirule_types.go
  apis/gateway/v1beta1/rule.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_timeout_integration_test.go
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller_integration_test.go
  docs/release-notes/2.1.1.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/technical-reference/05-20-api-rule-access-strategies.md
  internal/builders/access_rule.go
  internal/builders/access_rule_test.go
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/istio_suite_test.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/testsuites/istio-jwt/features/expose_methods_on_paths.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-custom-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/istio-default-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_multiple_mutators.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_mutators_overwrite.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/features/expose_methods_on_paths.feature
  tests/integration/testsuites/ory/manifests/custom-cors.yaml
  tests/integration/testsuites/ory/manifests/default-cors.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/ory/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#834 Cherrypick #830
  apis/gateway/v1beta1/apirule_types.go
  apis/gateway/v1beta1/rule.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_timeout_integration_test.go
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller_integration_test.go
  docs/release-notes/2.1.1.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/technical-reference/05-20-api-rule-access-strategies.md
  internal/builders/access_rule.go
  internal/builders/access_rule_test.go
  internal/builders/istio.go
  internal/builders/istio_test.go
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/internal/test/test_utils.go
  internal/processing/istio/access_rule_processor_test.go
  internal/processing/istio/authorization_policy_processor_test.go
  internal/processing/istio/istio_suite_test.go
  internal/processing/istio/request_authentication_processor_test.go
  internal/processing/istio/virtual_service_processor.go
  internal/processing/istio/virtual_service_processor_test.go
  internal/processing/ory/access_rule_processor_test.go
  internal/processing/ory/virtual_service_processor.go
  internal/processing/ory/virtual_service_processor_test.go
  internal/validation/validate.go
  internal/validation/validate_test.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/testsuites/istio-jwt/features/expose_methods_on_paths.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-custom-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/istio-default-cors.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/istio-jwt/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_multiple_mutators.go
  tests/integration/testsuites/istio-jwt/scenario_jwt_mutators_overwrite.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/istio-jwt/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/features/expose_methods_on_paths.feature
  tests/integration/testsuites/ory/manifests/custom-cors.yaml
  tests/integration/testsuites/ory/manifests/default-cors.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-allow-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-jwt-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-noop-handler.yaml
  tests/integration/testsuites/ory/manifests/multiple-paths-and-methods-oauth2-handler.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_allow.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_jwt.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_noop.go
  tests/integration/testsuites/ory/scenario_multiple_paths_and_methods_oauth2.go
  tests/integration/testsuites/ory/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#840 Update a link
  docs/contributor/01-00-installation.md
Labels: lgtm, size/XS, cla: yes

#841 Move APIRule Access Strategies doc and add it to the sidebar
  docs/user/_sidebar.md
  docs/user/custom-resources/README.md
  docs/user/custom-resources/apirule/04-15-api-rule-access-strategies.md
  docs/user/technical-reference/README.md
Labels: lgtm, size/XS, cla: yes

#842 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#843 Update sec-scanners-config.yaml
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#845 Fix script ref in job
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#850 Fix links
  docs/release-notes/2.1.1.md
  docs/user/custom-resources/apirule/04-15-api-rule-access-strategies.md
Labels: lgtm, size/XS, cla: yes

#846 Automated check for security scanner config
  .github/workflows/create-release.yaml
Labels: lgtm, size/S, cla: yes
