Repository kyma-project/api-gateway, pull requests merged in 2024-07, with the labels that each got.

#1136 Add Pre-Merge Checklist to the PR template
  .github/pull-request-template.md
Labels: lgtm, size/XS, cla: yes

#1135 Module Rollout Workflow
  .github/workflows/rollout-module.yaml
Labels: lgtm, size/L, cla: yes

#1137 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1142 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1152 Remove blank spaces
  docs/user/tutorials/01-20-set-up-tls-gateway.md
Labels: lgtm, size/XS, cla: yes

#1154 feat: more log gathering in int test jobs
  .github/actions/integration-test-gardener/action.yaml
  .github/actions/integration-tests/action.yaml
  tests/integration/pkg/helpers/api_rule.go
Labels: kind/feature, lgtm, size/M, area/ci, cla: yes

#1153 Remove empty spaces
  docs/user/tutorials/01-20-set-up-tls-gateway.md
Labels: lgtm, size/XS, cla: yes

#1158 Replace all context TODO
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_controller_status_integration_test.go
  controllers/gateway/apirule_controller_validation_integration_test.go
  controllers/gateway/apirule_timeout_integration_test.go
  controllers/gateway/suite_test.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/apigateway_controller_test.go
  controllers/operator/suite_test.go
  controllers/status_test.go
  internal/clusterconfig/clusterconfig_test.go
  internal/helpers/service_test.go
  internal/processing/cleaner_test.go
  internal/processing/processors/istio/authorization_policy_processor_test.go
  internal/processing/processors/ory/reconciliation_test.go
  internal/resources/resources_test.go
  internal/validation/v1beta1/v1beta1_test.go
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/custom-domain/testsuite.go
Labels: size/XL, lgtm, cla: yes

#1160 bug: increase retry attempts for all scenarios
  .github/actions/integration-test-gardener/action.yaml
  .github/actions/integration-tests/action.yaml
  tests/integration/pkg/testcontext/config.go
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1163 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1156 Add rules validation for v2alpha1
  controllers/gateway/config_map.go
  internal/validation/injection.go
  internal/validation/injection_test.go
  internal/validation/v1beta1/istio/jwt_validator_test.go
  internal/validation/v2alpha1/jwt.go
  internal/validation/v2alpha1/jwt_authentications_test.go
  internal/validation/v2alpha1/jwt_authorizations_test.go
  internal/validation/v2alpha1/jwt_test.go
  internal/validation/v2alpha1/rules.go
  internal/validation/v2alpha1/rules_test.go
  internal/validation/v2alpha1/sidecar_injection.go
  internal/validation/v2alpha1/sidecar_injection_test.go
  internal/validation/v2alpha1/suite_test.go
  internal/validation/v2alpha1/v2alpha1.go
  internal/validation/v2alpha1/v2alpha1_test.go
  main.go
Labels: lgtm, size/XXL, cla: yes

#1164 chore: add oathkeeper log collection
  .github/actions/integration-tests/action.yaml
Labels: lgtm, area/ci, size/XS, kind/chore, cla: yes

#1157 v2alpha1 CORS and Hosts
  apis/gateway/v2alpha1/rule.go
  controllers/gateway/api_controller_integration_test.go
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  internal/builders/virtual_service.go
  internal/builders/virtual_service_test.go
  internal/processing/processors/istio/virtual_service_processor.go
  internal/processing/processors/ory/virtual_service_processor.go
  internal/processing/processors/v2alpha1/cors_test.go
  internal/processing/processors/v2alpha1/hosts_test.go
  internal/processing/processors/v2alpha1/http_matching_test.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/test_builders_test.go
  internal/processing/processors/v2alpha1/timeout_test.go
  internal/processing/processors/v2alpha1/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtual_service_processor_test.go
Labels: size/XL, lgtm, cla: yes

#1165 APIRule hosts should be FQDN
  controllers/gateway/apirule_controller.go
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/processing/processors/v2alpha1/status_test.go
  internal/validation/v2alpha1/hosts.go
  internal/validation/v2alpha1/hosts_test.go
  internal/validation/v2alpha1/v2alpha1.go
  internal/validation/v2alpha1/v2alpha1_test.go
Labels: size/XL, lgtm, cla: yes

#1169 Add V2alpha1 integration tests
  Makefile
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  internal/processing/processors/v2alpha1/reconciliation.go
  tests/integration/main_test.go
  tests/integration/testsuites/v2alpha1/features/cors.feature
  tests/integration/testsuites/v2alpha1/features/expose_methods_on_paths.feature
  tests/integration/testsuites/v2alpha1/features/jwt.feature
  tests/integration/testsuites/v2alpha1/features/service.feature
  tests/integration/testsuites/v2alpha1/manifests/cors-custom.yaml
  tests/integration/testsuites/v2alpha1/manifests/cors-default.yaml
  tests/integration/testsuites/v2alpha1/manifests/global-commons.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-and-unrestricted.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-audiences.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-common.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-issuer-jwks-not-match.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-scopes.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-token-from-header.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-token-from-param.yaml
  tests/integration/testsuites/v2alpha1/manifests/jwt-unavailable-issuer.yaml
  tests/integration/testsuites/v2alpha1/manifests/paths-and-methods-jwt.yaml
  tests/integration/testsuites/v2alpha1/manifests/paths-and-methods-noauth.yaml
  tests/integration/testsuites/v2alpha1/manifests/second-service.yaml
  tests/integration/testsuites/v2alpha1/manifests/service-custom-label-selector.yaml
  tests/integration/testsuites/v2alpha1/manifests/service-diff-same-methods.yaml
  tests/integration/testsuites/v2alpha1/manifests/service-fallback.yaml
  tests/integration/testsuites/v2alpha1/manifests/service-two-namespaces.yaml
  tests/integration/testsuites/v2alpha1/manifests/testing-app.yaml
  tests/integration/testsuites/v2alpha1/manifests/testing-helloworld-app.yaml
  tests/integration/testsuites/v2alpha1/manifests/testing-helloworld-custom-label-app.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_cors_custom.go
  tests/integration/testsuites/v2alpha1/scenario_cors_default.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_and_unrestricted.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_audience.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_common.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_issuer_jwks_not_match.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_scopes.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_header.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_param.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_unavailable_issuer.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_jwt.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_noauth.go
  tests/integration/testsuites/v2alpha1/scenario_service_custom_label_selector.go
  tests/integration/testsuites/v2alpha1/scenario_service_diff_same_methods.go
  tests/integration/testsuites/v2alpha1/scenario_service_fallback.go
  tests/integration/testsuites/v2alpha1/scenario_service_two_namespaces.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#1174 Remove deprecation warning for APIRule v1beta1
  apis/gateway/v1beta1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, size/XS, cla: yes

#1170 API Rule version migration mode
  controllers/gateway/apirule_controller.go
  controllers/gateway/reconcile_result.go
  controllers/gateway/types.go
  docs/release-notes/2.4.0.md
  docs/user/custom-resources/apirule/v2alpha1/04-60-apirule-migration.md
  docs/user/technical-reference/05-00-api-gateway-operator-parameters.md
  internal/processing/processors/migration/access_rule_deletion.go
  internal/processing/processors/migration/access_rule_deletion_test.go
  internal/processing/processors/migration/annotation.go
  internal/processing/processors/migration/annotation_test.go
  internal/processing/processors/migration/processors.go
  internal/processing/processors/migration/processors_test.go
  internal/processing/processors/migration/suite_test.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/processing/processors/v2alpha1/status_test.go
  internal/processing/processors/v2alpha1/virtualservice/cors_test.go
  internal/processing/processors/v2alpha1/virtualservice/hosts_test.go
  internal/processing/processors/v2alpha1/virtualservice/http_matching_test.go
  internal/processing/processors/v2alpha1/virtualservice/suite_test.go
  internal/processing/processors/v2alpha1/virtualservice/test_builders_test.go
  internal/processing/processors/v2alpha1/virtualservice/timeout_test.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
  main.go
  tests/integration/main_test.go
  tests/integration/pkg/resource/manager.go
  tests/integration/testsuites/gateway/scenario.go
  tests/integration/testsuites/ory/features/v2alpha1_conversion.feature
  tests/integration/testsuites/ory/manifests/testing-app-istio-injection.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_migration_jwt_v1beta1.go
  tests/integration/testsuites/ory/testsuite.go
Labels: size/XL, lgtm, cla: yes

#1176 Security scanner config update
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1172 Release notes for API Gateway 2.4.0
  docs/release-notes/2.4.0.md
Labels: lgtm, size/S, cla: yes

#1180 Update sec-scanners-config.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1179 Allow access with NoAuth on JWT secured workload
  internal/processing/helpers.go
  internal/processing/processors/istio/authorization_policy_processor.go
  internal/processing/processors/istio/authorization_policy_processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  tests/integration/main_test.go
  tests/integration/testsuites/istio-jwt/features/Istio_jwt_two_strategies.feature
  tests/integration/testsuites/istio-jwt/manifests/istio-jwt-and-no-auth.yaml
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_noauth_and_jwt.go
  tests/integration/testsuites/istio-jwt/testsuite.go
Labels: lgtm, size/L, cla: yes

#1182 Add empty spec troubleshooting
  docs/user/troubleshooting-guides/03-70-empty-apirule-spec.md
Labels: lgtm, size/S, cla: yes

#1181 Drop image build and wait from prow
  .github/actions/build-manager-image/action.yaml
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/load-manager-image/action.yaml
  .github/actions/upgrade-test/action.yaml
  .github/workflows/pull-build-push.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/ui-tests-periodic.yaml
  .github/workflows/ui-tests.yaml
  controllers/operator/apigateway_controller_test.go
  docs/contributor/04-30-ci-cd.md
  tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
Labels: lgtm, size/L, cla: yes

#1186 Update a broken link
  docs/release-notes/2.4.0.md
Labels: lgtm, size/XS, cla: yes

#1188 bug: add name to port in service.yaml
  config/conversion_webhook/service.yaml
Labels: kind/bug, lgtm, area/api-gateway, size/XS, cla: yes

#1190 Fix main int upgrade int test input
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1189 Fix webhook bug
  config/conversion_webhook/service.yaml
  docs/release-notes/2.4.1.md
Labels: lgtm, size/XS, cla: yes

#1191 chore: sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1196 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1199 Exclude Secret resources from manage client cache
  main.go
Labels: lgtm, size/XS, cla: yes

#1202 Add docs to the sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, cla: yes

#1203 bug: fix unbound variable in checking for apiserver
  tests/integration/scripts/provision-gardener-gh.sh
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1206 Change enable and disable to add and delete in the api-gateway repo
  docs/user/README.md
Labels: lgtm, size/XS, cla: yes

#1201 feat: APIGateway periodic reconciliation
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_test.go
  docs/contributor/04-10-technical-design.md
Labels: lgtm, size/M, cla: yes

#1204 Fix list-watch options for controller manager for Secrets to look only in kyma-system namespace
  config/manager/manager.yaml
  controllers/certificate/certificate_secret.go
  main.go
  tests/integration/testsuites/upgrade/manifests/upgrade-test-operator-fail.yaml
Labels: lgtm, size/S, cla: yes

#1209 Release 2.4.2
  VERSION
  config/manager/manager.yaml
  controllers/certificate/certificate_secret.go
  docs/release-notes/2.4.2.md
  main.go
  sec-scanners-config.yaml
  tests/integration/testsuites/upgrade/manifests/upgrade-test-operator-fail.yaml
Labels: lgtm, size/S, cla: yes
