Repository kyma-project/api-gateway, pull requests merged in 2024-09, with the labels that each got.

#1276 Update security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1246 feat: handling v2alpha1 APIRule version status
  apis/gateway/v1beta1/apirule_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  apis/gateway/v2alpha1/apirule_types.go
  apis/gateway/v2alpha1/zz_generated.deepcopy.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  controllers/gateway/apirule_controller.go
  controllers/gateway/apirule_deletion.go
  controllers/gateway/reconcile_result.go
  controllers/status.go
  internal/processing/processors/migration/annotation.go
  internal/processing/processors/migration/annotation_test.go
  internal/processing/processors/migration/processors.go
  internal/processing/processors/migration/processors_test.go
  internal/processing/processors/v2alpha1/reconciliation.go
  internal/processing/processors/v2alpha1/status.go
  internal/processing/processors/v2alpha1/status_test.go
  internal/processing/reconciliation.go
  internal/processing/status/status.go
  internal/processing/status/status_test.go
  internal/processing/status/v1beta1.go
  internal/processing/status/v2alpha1.go
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/testsuites/gateway/scenario.go
  tests/integration/testsuites/v2alpha1/features/validation.feature
  tests/integration/testsuites/v2alpha1/manifests/validation-error.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_validation_error.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: kind/feature, size/XL, lgtm, area/api-gateway, cla: yes

#1286 feat: replace getting converted resource in reconcile
  apis/gateway/v2alpha1/apirule_conversion.go
  controllers/gateway/apirule_controller.go
  controllers/gateway/apirule_deletion.go
  controllers/gateway/reconcile_result.go
  internal/processing/reconciliation.go
  internal/processing/reconciliation_test.go
Labels: kind/feature, lgtm, area/api-gateway, size/L, cla: yes

#1290 chore: switch main build jobs
  .github/workflows/main-integration.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, size/M, area/api-gateway, kind/chore, cla: yes

#1289 Add more logs to resource operations
  hack/ci/provision-gardener.sh
  tests/integration/pkg/resource/manager.go
Labels: lgtm, size/M, cla: yes

#1293 bug: fix typo in main-integration.yaml
  .github/workflows/main-integration.yaml
Labels: kind/bug, lgtm, area/api-gateway, size/XS, cla: yes

#1294 Validate that at least one provider exists in ext-auth config
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
Labels: lgtm, size/XS, cla: yes

#1298 Release API Gateway 2.6.0
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1302 Bump dependabot config for 2.6.0 release
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1305 Update manager tag in sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1310 Adjust migration notes
  docs/user/custom-resources/README.md
  docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
  docs/user/custom-resources/apirule/README.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/README.md
  docs/user/tutorials/01-40-expose-workload/README.md
  docs/user/tutorials/01-50-expose-and-secure-a-workload/README.md
Labels: lgtm, size/S, cla: yes

#1312 Zero downtime migration tests
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  Makefile
  docs/contributor/04-30-ci-cd.md
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  tests/integration/main_test.go
  tests/integration/scripts/test-zero-downtime.sh
  tests/integration/testsuites/ory/features/v2alpha1_conversion.feature
  tests/integration/testsuites/ory/manifests/migration-allow-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-allow-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-jwt-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-jwt-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-noauth-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-noauth-v2alpha1.yaml
  tests/integration/testsuites/ory/manifests/migration-noop-v1beta1.yaml
  tests/integration/testsuites/ory/manifests/migration-noop-v2alpha1.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_migration_allow_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_jwt_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noauth_v1beta1.go
  tests/integration/testsuites/ory/scenario_migration_noop_v1beta1.go
Labels: lgtm, size/L, cla: yes

#1317 Add links for Zero Downtime Migration Tests in CI/CD docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1318 Ensure shot host with ref gateway domain used for occupied vs check
  internal/validation/v2alpha1/hosts.go
  internal/validation/v2alpha1/hosts_test.go
Labels: lgtm, size/L, cla: yes

#1320 Move build to separate job in main int test
  .github/workflows/main-integration.yaml
Labels: lgtm, size/M, cla: yes

#1323 Run integration tests in schedule without build
  .github/workflows/main-integration.yaml
Labels: lgtm, size/M, cla: yes

#1324 Add image-builder to create release workflow
  .github/workflows/create-release.yaml
Labels: lgtm, size/S, cla: yes

#1326 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1327 bug: enable experimentalMemoryManagement in cypress
  tests/ui/tests/cypress.config.ts
Labels: kind/bug, lgtm, area/api-gateway, size/XS, cla: yes

#1316 ExtAuth oauth2-proxy tutorial with Client Credentials flow
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-53-expose-and-secure-workload-ext-auth.md
Labels: lgtm, size/L, cla: yes

#1333 Update CI/CD documentation with new build job
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes
