Repository kyma-project/api-gateway, pull requests merged in 2024-11, with the labels that each got.

#1411 Introduce support for the path operators `{*}` and `{**}`
  apis/gateway/v2alpha1/apirule_types.go
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  docs/release-notes/2.9.0.md
  docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
  internal/validation/v2alpha1/rules.go
  internal/validation/v2alpha1/rules_test.go
  tests/integration/main_test.go
  tests/integration/testsuites/v2alpha1/features/asterisk.feature
  tests/integration/testsuites/v2alpha1/manifests/asterisk-paths.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_asterisk.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: size/L, cla: yes

#1416 Improved resiliency of custom domain integration tests
  hack/ci/custom-domain-gardener-aws.sh
  hack/ci/custom-domain-gardener-gcp.sh
  hack/ci/custom-domain-gardener.sh
  hack/ci/provision-gardener.sh
Labels: lgtm, size/M, cla: yes

#1415 hack: consolidate pull-request status into one job
  .github/workflows/pull-build-push.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/pull-unit-lint.yaml
  .github/workflows/ui-tests.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, area/ci, size/L, kind/chore, cla: yes

#1424 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: lgtm, size/M, cla: yes

#1426 bug: change any_changed to any_modified and add back output
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-unit-lint.yaml
  .github/workflows/ui-tests.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#1422 Validation of path conflicts with `{**}` or `{*}` operators
  internal/path/segment_trie/segment_trie.go
  internal/path/segment_trie/segment_trie_test.go
  internal/path/token/token.go
  internal/path/token/token_test.go
  internal/validation/v2alpha1/rules.go
  internal/validation/v2alpha1/rules_test.go
Labels: size/XL, lgtm, cla: yes

#1427 Fix issue template
  .github/ISSUE_TEMPLATE/issue.md
Labels: lgtm, size/S, cla: yes

#1431 bug: add GITHUB_TOKEN as env variable to actions
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/pull-unit-lint.yaml
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1435 bug: fix incorrect secret usage
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
Labels: kind/bug, lgtm, size/M, area/ci, cla: yes

#1436 bug: fix incorrect secret usage (#1435)
  .github/actions/integration-tests/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/ui-tests.yaml
Labels: kind/bug, lgtm, size/M, area/ci, cla: yes

#1442 Bump api-gateway-manager main image for sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1445 bug: add export of image-builder built artifact
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, lgtm, size/M, area/ci, cla: yes

#1446 bug: add export of image-builder built artifact
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#1447 bug: add export of image-builder built artifact
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#1433 Update sec-scanners-config.yaml and version for APIGateway 2.9.0
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1441 bug: add export of image-builder built artifact
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#1432 Documentation for path conflict validation
  docs/assets/segment-trie.svg
  docs/contributor/02-00-path-validation.md
Labels: lgtm, size/L, cla: yes

#1434 chore: separate main and release images
  .github/workflows/create-release.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/ui-tests-periodic.yaml
  scripts/publish_assets.sh
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1448 Add APIRules v1beta1 deprecation information in the UI
  config/ui-extensions/apirules/injections
  config/ui-extensions/apirules/kustomization.yaml
  docs/release-notes/2.10.0.md
  tests/ui/tests/support/apirule.ts
  tests/ui/tests/support/combobox.ts
Labels: lgtm, size/M, cla: yes

#1449 chore: update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/ci, size/XS, kind/chore, cla: yes

#1452 Update release branch in Dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1457 Increase test request timeout for custom domain tests
  tests/integration/env_vars_custom_domain.sh
Labels: lgtm, size/XS, cla: yes

#1451 Feature toggle for rate limiting
  Dockerfile
  Makefile
  PROJECT
  apis/ratelimit/v1alpha1/groupversion_info.go
  apis/ratelimit/v1alpha1/ratelimit_types.go
  apis/ratelimit/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ratelimit.kyma-project.io_ratelimits.yaml
  config/crd/kustomization.yaml
  config/dev/kustomization.yaml
  config/prod/kustomization.yaml
  config/samples/ratelimit_v1alpha1_ratelimit.yaml
  controllers/ratelimit/feature_disabled.go
  controllers/ratelimit/feature_enabled.go
  controllers/ratelimit/ratelimit_controller.go
  controllers/ratelimit/ratelimit_controller_test.go
  controllers/ratelimit/suite_test.go
  main.go
Labels: size/XL, lgtm, cla: yes

#1462 Increase timeout for provisioning Gardener cluster
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1463 Add pod antiaffinity to oathkeeper pods (HA/multi-az support)
  docs/contributor/04-10-technical-design.md
  docs/release-notes/2.11.0.md
  internal/reconciliations/oathkeeper/deployment.yaml
Labels: lgtm, size/S, cla: yes

#1466 Reduce UI test flakiness
  tests/ui/tests/cypress.config.ts
  tests/ui/tests/support/navigation.ts
Labels: lgtm, size/S, cla: yes

#1471 Move 2.11.0 release notes to 2.10.0
  docs/release-notes/2.10.0.md
  docs/release-notes/2.11.0.md
Labels: lgtm, size/XS, cla: yes

#1475 Update sec scanner config and VERSION file for release
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1476 Update security scanner config
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1477 Update dependabot for rel 2.10
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1483 chore: remove custom labels from dependabot.yml
  .github/dependabot.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1486 Reduce flakiness of custom domain tests
  tests/integration/env_vars_custom_domain.sh
  tests/integration/pkg/testcontext/config.go
Labels: lgtm, size/XS, cla: yes

#1489 feat: workflow to add dependabot PRs to project
  .github/workflows/pr-add-dependabot-to-project.yaml
Labels: kind/feature, area/ci, size/L, cla: yes

#1487 Move rate limit ADR from Istio Module repository
  docs/contributor/adr/0011-rate-limit.md
Labels: lgtm, size/L, cla: yes

#1494 Replace 'remedy' with 'solution' in the troubleshooting guides
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-01-401-unauthorized-403-forbidden.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-02-404-not-found.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-03-500-server-error.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/03-40-api-rule-troubleshooting.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v2alpha1/03-01-401-unauthorized-403-forbidden.md
  docs/user/troubleshooting-guides/03-00-cannot-connect-to-service/v2alpha1/03-40-api-rule-troubleshooting.md
  docs/user/troubleshooting-guides/03-10-dns-mgt/03-10-dns-mgt-connection-refused.md
  docs/user/troubleshooting-guides/03-10-dns-mgt/03-11-dns-mgt-could-not-resolve-host.md
  docs/user/troubleshooting-guides/03-10-dns-mgt/03-12-dns-mgt-resource-ignored.md
  docs/user/troubleshooting-guides/03-20-cert-mgt-issuer-not-created.md
  docs/user/troubleshooting-guides/03-30-gateway-not-reachable.md
  docs/user/troubleshooting-guides/03-50-certificates-gardener.md
  docs/user/troubleshooting-guides/03-60-apirule-conversion-webhook-cert-issue.md
  docs/user/troubleshooting-guides/03-70-empty-apirule-spec.md
Labels: lgtm, size/M, cla: yes

#1488 Add Oathkeeper logs in integration tests
  tests/integration/pkg/oathkeeper/log.go
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/M, cla: yes

#1493 feat: add testing in create-release.yaml
  .github/workflows/create-release.yaml
  .github/workflows/integration-release.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/unit-lint.yaml
Labels: kind/feature, lgtm, size/M, area/ci, cla: yes

#1492 Custom domain tests with KUBECONFIG env variable
  hack/ci/custom-domain-gardener.sh
  hack/ci/provision-gardener.sh
  tests/integration/env_vars_custom_domain.sh
Labels: lgtm, size/S, cla: yes

#1491 Test sanity checks
  Makefile
  tests/integration/main_test.go
  tests/integration/pkg/auth/oauth2-server-mock.go
  tests/integration/pkg/auth/oauth2-server-mock.yaml
  tests/integration/pkg/auth/oauth2-server.go
  tests/integration/pkg/global/global.go
  tests/integration/pkg/helpers/deployment.go
  tests/integration/pkg/helpers/file.go
  tests/integration/pkg/helpers/gardener.go
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/pkg/hooks/ext-auth.go
  tests/integration/pkg/testcontext/config.go
  tests/integration/pkg/testcontext/config_validation.go
  tests/integration/pkg/testcontext/testsuite.go
  tests/integration/testsuites/custom-domain/features/custom_domain.feature
  tests/integration/testsuites/custom-domain/manifests/resources.yaml
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/custom-domain/testsuite.go
  tests/integration/testsuites/gateway/testsuite.go
  tests/integration/testsuites/istio-jwt/testsuite.go
  tests/integration/testsuites/ory/testsuite.go
  tests/integration/testsuites/upgrade/testsuite.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#1500 Fixed failing tests: base64 encoding with padding
  tests/integration/pkg/auth/oauth2-server.go
  tests/integration/testsuites/custom-domain/scenario.go
Labels: lgtm, size/XS, cla: yes

#1501 Adding KYMA_DOMAIN variable into custom-domain.gardener.sh, so it is visible to other make targets
  hack/ci/custom-domain-gardener.sh
Labels: lgtm, size/XS, cla: yes
