Repository kyma-project/api-gateway, pull requests merged in 2025-01, with the labels that each got.

#1569 Full support for special characters in asterisk paths
  apis/gateway/v2alpha1/apirule_types.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/processing/processors/v2alpha1/virtualservice/regex_test.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
  tests/integration/testsuites/v2alpha1/features/asterisk.feature
Labels: lgtm, size/L, cla: yes

#1576 Fix a broken link
  docs/user/tutorials/01-50-expose-and-secure-a-workload/01-55-ip-based-access-with-xff.md
Labels: lgtm, size/XS, cla: yes

#1580 chore: version 2.10.2
  VERSION
  apis/gateway/v2alpha1/apirule_types.go
  controllers/gateway/apirule_controller.go
  controllers/gateway/suite_test.go
  controllers/gateway/types.go
  docs/release-notes/2.10.2.md
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  internal/processing/processors/v2alpha1/virtualservice/regex_test.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor.go
  internal/processing/processors/v2alpha1/virtualservice/virtual_service_processor_test.go
  main.go
  tests/integration/main_test.go
  tests/integration/pkg/helpers/string.go
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/testsuites/v2alpha1/features/asterisk.feature
  tests/integration/testsuites/v2alpha1/features/cors.feature
  tests/integration/testsuites/v2alpha1/features/expose_methods_on_paths.feature
  tests/integration/testsuites/v2alpha1/features/ext_auth.feature
  tests/integration/testsuites/v2alpha1/features/jwt.feature
  tests/integration/testsuites/v2alpha1/features/no_auth.feature
  tests/integration/testsuites/v2alpha1/features/request.feature
  tests/integration/testsuites/v2alpha1/features/service.feature
  tests/integration/testsuites/v2alpha1/features/short_host.feature
  tests/integration/testsuites/v2alpha1/features/validation.feature
  tests/integration/testsuites/v2alpha1/manifests/global-commons.yaml
  tests/integration/testsuites/v2alpha1/manifests/second-service.yaml
  tests/integration/testsuites/v2alpha1/manifests/testing-app.yaml
  tests/integration/testsuites/v2alpha1/scenario.go
  tests/integration/testsuites/v2alpha1/scenario_asterisk.go
  tests/integration/testsuites/v2alpha1/scenario_cors_custom.go
  tests/integration/testsuites/v2alpha1/scenario_cors_default.go
  tests/integration/testsuites/v2alpha1/scenario_ext_auth.go
  tests/integration/testsuites/v2alpha1/scenario_initializers.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_and_unrestricted.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_audience.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_common.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_issuer_jwks_not_match.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_scopes.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_header.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_token_param.go
  tests/integration/testsuites/v2alpha1/scenario_jwt_unavailable_issuer.go
  tests/integration/testsuites/v2alpha1/scenario_no_auth.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_jwt.go
  tests/integration/testsuites/v2alpha1/scenario_paths_and_methods_noauth.go
  tests/integration/testsuites/v2alpha1/scenario_request_modification.go
  tests/integration/testsuites/v2alpha1/scenario_service_custom_label_selector.go
  tests/integration/testsuites/v2alpha1/scenario_service_diff_same_methods.go
  tests/integration/testsuites/v2alpha1/scenario_service_fallback.go
  tests/integration/testsuites/v2alpha1/scenario_service_two_namespaces.go
  tests/integration/testsuites/v2alpha1/scenario_short_host.go
  tests/integration/testsuites/v2alpha1/scenario_validation_error.go
  tests/integration/testsuites/v2alpha1/testsuite.go
Labels: lgtm, size/XXL, cla: yes

#1581 Bug fix: don't constantly update APIRule in tests while getting the status
  tests/integration/main_test.go
  tests/integration/pkg/helpers/api_rule.go
  tests/integration/pkg/helpers/loadbalancer.go
  tests/integration/pkg/helpers/response_validation.go
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/pkg/network/dns.go
  tests/integration/testsuites/custom-domain/features/custom_domain.feature
  tests/integration/testsuites/custom-domain/manifests/no-access-strategy.yaml
  tests/integration/testsuites/custom-domain/manifests/oauth-strategy.yaml
  tests/integration/testsuites/custom-domain/manifests/resources.yaml
  tests/integration/testsuites/custom-domain/scenario.go
  tests/integration/testsuites/custom-domain/testsuite.go
  tests/integration/testsuites/istio-jwt/features/Istio_jwt_two_strategies.feature
  tests/integration/testsuites/istio-jwt/scenario.go
  tests/integration/testsuites/istio-jwt/scenario_noauth_and_jwt.go
  tests/integration/testsuites/ory/features/service_per_path.feature
  tests/integration/testsuites/ory/manifests/service-per-path.yaml
  tests/integration/testsuites/ory/manifests/testing-app-helloworld.yaml
  tests/integration/testsuites/ory/scenario.go
  tests/integration/testsuites/ory/scenario_secured_to_unsecured.go
  tests/integration/testsuites/ory/scenario_service_per_path.go
  tests/integration/testsuites/ory/scenario_unsecured_to_secured_oauth_jwt.go
  tests/integration/testsuites/upgrade/scenario.go
  tests/integration/testsuites/v2alpha1/scenario.go
Labels: size/XL, lgtm, cla: yes

#1589 chore: bump sec-scanners-config.yaml to 2.10.2
  sec-scanners-config.yaml
Labels: area/api-gateway, size/XS, kind/chore, cla: yes

#1591 Changed get-latest-sha to get more recent image
  .github/actions/get-latest-sha/action.yaml
Labels: lgtm, size/XS, cla: yes

#1594 Improved zero downtime test script - increased waiting time, avoided race condition, better logging
  tests/integration/scripts/test-zero-downtime.sh
Labels: lgtm, size/M, cla: yes

#1596 Fix ApiRule path in docs in tutorial.
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
Labels: lgtm, size/XS, cla: yes

#1601 tests: added a hook that waits for the apigateway dependencies to be removed
  tests/integration/pkg/hooks/api-gateway.go
  tests/integration/testsuites/gateway/scenario.go
Labels: lgtm, size/M, cla: yes

#1602 feat: extend APIGateway blocking deletion with RateLimit resource
  controllers/gateway/ratelimit/ratelimit_disabled.go
  controllers/gateway/ratelimit/ratelimit_enabled.go
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  controllers/operator/suite_test.go
Labels: lgtm, size/L, cla: yes

#1610 Fix code block formatting in the JWT tutorial
  docs/user/tutorials/01-50-expose-and-secure-a-workload/v2alpha1/01-52-expose-and-secure-workload-jwt.md
Labels: lgtm, size/M, cla: yes

#1603 tests: annotate Gardener clusters with pipeline link, store shoot yaml
  .github/actions/e2e-test-gardener/action.yaml
  .github/actions/k8s-compatibility-test-aws/action.yaml
  hack/ci/provision-gardener.sh
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
Labels: lgtm, size/M, cla: yes

#1605 BTP provision QOL additions
  .github/workflows/call-provision-btp-cluster.yaml
Labels: lgtm, size/M, cla: yes

#1615 Adjust name for schedule job
  .github/workflows/schedule-main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1616 Increase timeout for the Gardener provisioning
  hack/ci/provision-gardener.sh
Labels: lgtm, size/M, cla: yes

#1621 Allow for exposing of same path without "/" if already exposed using wildcard
  internal/path/segment_trie/segment_trie.go
  internal/path/segment_trie/segment_trie_test.go
Labels: lgtm, size/S, cla: yes

#1620 Cleanup ci-cd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1625 [backport 2.10] Allow for exposing of same path without "/" if already exposed using wildcard
  internal/path/segment_trie/segment_trie.go
  internal/path/segment_trie/segment_trie_test.go
Labels: lgtm, size/S, cla: yes

#1600 fix: Generate manifest for APIRule
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: lgtm, size/XS, cla: yes

#1633 bug: fix bucket validation in ratelimit_types.go
  apis/gateway/ratelimit/v1alpha1/ratelimit_types.go
  config/crd/bases/gateway.kyma-project.io_ratelimits.yaml
  controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
Labels: kind/bug, lgtm, area/api-gateway, size/L, cla: yes

#1627 bug: fix duration parse in ratelimit.go
  internal/ratelimit/ratelimit.go
  internal/ratelimit/ratelimit_test.go
  internal/ratelimit/testdata/envoy_patches.yaml
  internal/ratelimit/validate.go
  internal/ratelimit/validate_test.go
Labels: kind/bug, lgtm, size/M, area/api-gateway, cla: yes

#1631 docs: ratelimit tutorials
  docs/user/tutorials/01-70-rate-limit.md
  docs/user/tutorials/README.md
Labels: kind/feature, lgtm, area/documentation, area/api-gateway, size/L, cla: yes

#1628 Update tutorial
  docs/user/tutorials/01-10-setup-custom-domain-for-workload.md
Labels: lgtm, size/XS, cla: yes

#1636 bug: fix ratelimit multiple error
  internal/ratelimit/validate.go
  internal/ratelimit/validate_test.go
Labels: kind/bug, lgtm, size/M, area/api-gateway, cla: yes

#1640 Bump k8s version in tests
  .github/actions/k8s-compatibility-test/action.yaml
  hack/ci/set-aws-gardener.sh
  hack/ci/set-gcp-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1647 Fix wrong jwks algorithm
  internal/reconciliations/oathkeeper/jwks_secret.go
Labels: lgtm, size/XS, cla: yes

#1644 Remove rate limit toggle
  Dockerfile
  Makefile
  config/dev/kustomization.yaml
  config/prod/kustomization.yaml
  controllers/gateway/ratelimit/ratelimit_controller.go
  controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
  controllers/gateway/ratelimit/ratelimit_disabled.go
  controllers/gateway/ratelimit/ratelimit_enabled.go
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
  docs/release-notes/2.11.0.md
  main.go
Labels: lgtm, size/L, cla: yes

#1649 tests: delete custom domain resources in reversed order
  tests/integration/testsuites/custom-domain/testsuite.go
Labels: lgtm, size/XS, cla: yes

#1641 test: rate limit e2e tests
  .github/workflows/call-integration-release.yaml
  .github/workflows/call-pull-integration.yaml
  .github/workflows/post-main-integration.yaml
  .github/workflows/schedule-main-integration.yaml
  Makefile
  tests/integration/main_test.go
  tests/integration/pkg/helpers/http_client.go
  tests/integration/pkg/helpers/rate_limit.go
  tests/integration/testsuites/rate-limit/features/local_rate_limit.feature
  tests/integration/testsuites/rate-limit/manifests/api-gateway.yaml
  tests/integration/testsuites/rate-limit/manifests/global-commons.yaml
  tests/integration/testsuites/rate-limit/manifests/ratelimit-header-based.yaml
  tests/integration/testsuites/rate-limit/manifests/ratelimit-path-and-header-based.yaml
  tests/integration/testsuites/rate-limit/manifests/ratelimit-path-based.yaml
  tests/integration/testsuites/rate-limit/manifests/testing-app.yaml
  tests/integration/testsuites/rate-limit/scenario.go
  tests/integration/testsuites/rate-limit/scenario_initializers.go
  tests/integration/testsuites/rate-limit/testsuite.go
Labels: size/XL, lgtm, cla: yes

#1650 Remove redundant get-sha job in the post workflow
  .github/workflows/post-main-integration.yaml
Labels: lgtm, size/M, cla: yes

#1653 docs: add ratelimit notice
  docs/user/tutorials/01-70-local-rate-limit.md
  docs/user/tutorials/README.md
Labels: lgtm, size/XS, cla: yes
