Repository kyma-project/api-gateway, pull requests merged in 2025-03, with the labels that each got.

#1748 chore: update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S

#1749 Update dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS

#1760 Fix links
  docs/contributor/adr/0007-apirule-v2alpha1-api-proposal.md
  docs/user/_sidebar.md
Labels: lgtm, size/S

#1767 Add missing permission for release pipeline
  .github/workflows/release-create-release.yaml
Labels: lgtm, size/XS

#1768 Add missing permission for release pipeline (#1767)
  .github/workflows/release-create-release.yaml
Labels: lgtm, size/XS

#1751 docs: update migration guide
  docs/user/custom-resources/apirule/04-60-apirule-migration.md
  docs/user/custom-resources/apirule/04-70-changes-in-apirule-v2.md
Labels: lgtm, size/M

#1776 Add in-cluster connectivity test
  tests/integration/pkg/client/client.go
  tests/integration/pkg/helpers/curl.go
  tests/integration/testsuites/v2/features/jwt.feature
  tests/integration/testsuites/v2/features/no_auth.feature
  tests/integration/testsuites/v2/features/service.feature
  tests/integration/testsuites/v2/scenario.go
  tests/integration/testsuites/v2/scenario_initializers.go
Labels: size/L

#1774 Adjust filters for apirule v2 and v1beta1
  config/ui-extensions/apirules-v1beta1/general
  config/ui-extensions/apirules/general
Labels: size/XS

#1773 bug: enqueue apirules reconcile on svc changes
  controllers/gateway/api_controller_integration_test.go
  controllers/gateway/apirule_controller.go
  tests/integration/pkg/hooks/api-gateway.go
Labels: size/L

#1790 Remove tj-actions/changed-files
  .github/workflows/call-pull-integration.yaml
  .github/workflows/call-ui-tests.yaml
  .github/workflows/call-verify-commit-pins.yaml
Labels: dependencies, github_actions

#1759 Enable watch for istio-ingressgateway service
  controllers/operator/apigateway_controller.go
  controllers/operator/apigateway_controller_integration_test.go
Labels: size/M
