Repository kyma-project/api-gateway, pull requests merged in 2025-02, with the labels that each got.

#1658 Fix wrong jwks algorithm (#1647)
  internal/reconciliations/oathkeeper/jwks_secret.go
Labels: lgtm, size/XS, cla: yes

#1657 add-release-notes
  docs/release-notes/2.10.3.md
Labels: lgtm, size/XS, cla: yes

#1661 chore: prepare 2.10.3
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, area/api-gateway, size/XS, kind/chore, cla: yes

#1664 bug: fix yq fetch on noble runners
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, area/api-gateway, size/S, cla: yes

#1665 bug: remove yq from release-create-release.yaml
  .github/workflows/release-create-release.yaml
  Makefile
Labels: kind/bug, lgtm, area/api-gateway, size/S, cla: yes

#1672 Update failing workflow
  .github/workflows/call-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1671 Update failing workflow
  .github/workflows/call-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1677 Fix branch for upgrade tests
  .github/workflows/call-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1681 Switch region for CCEE
  .github/workflows/call-provision-btp-cluster.yaml
Labels: lgtm, size/XS, cla: yes

#1666 Enable internal traffic for workloads exposed by v2alpha1 APIRule
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
Labels: lgtm, size/L, cla: yes

#1686 [backport 2.10] Enable internal traffic for workloads exposed by v2alpha1 APIRule
  docs/release-notes/2.10.4.md
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
Labels: lgtm, size/L, cla: yes

#1687 [backport 2.11] Enable internal traffic for workloads exposed by v2alpha1 APIRule
  docs/release-notes/2.11.1.md
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
Labels: lgtm, size/L, cla: yes

#1692 [2.11.1] Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1693 Add checks of APIgatewayCR before RateLimitCR
  apis/operator/v1alpha1/apigateway_types.go
  controllers/gateway/ratelimit/ratelimit_controller.go
  controllers/gateway/ratelimit/ratelimit_controller_integration_test.go
  controllers/operator/apigateway_controller.go
Labels: size/XL, lgtm, cla: yes

#1705 Revert "Enable internal traffic for workloads exposed by v2alpha1 APIRule"
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
Labels: lgtm, size/L, cla: yes

#1706 Reverting fix for the issue https://github.com/kyma-project/api-gateway/issues/1632
  docs/release-notes/2.10.5.md
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  tests/integration/testsuites/custom-domain/manifests/testing-app.yaml
  tests/integration/testsuites/istio-jwt/manifests/testing-app.yaml
  tests/integration/testsuites/ory/manifests/testing-app-istio-injection.yaml
  tests/integration/testsuites/ory/manifests/testing-app.yaml
  tests/integration/testsuites/upgrade/manifests/testing-app.yaml
Labels: lgtm, size/L, cla: yes

#1707 Reverting fix for the issue https://github.com/kyma-project/api-gateway/issues/1632
  docs/release-notes/2.11.2.md
  docs/release-notes/2.12.0.md
  internal/builders/istio.go
  internal/processing/processors/v2alpha1/authorizationpolicy/audience_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/creator.go
  internal/processing/processors/v2alpha1/authorizationpolicy/ext_auth_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/internal_access_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/jwt_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/no_auth_rules_test.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor.go
  internal/processing/processors/v2alpha1/authorizationpolicy/processor_test.go
  internal/processing/processors/v2alpha1/reconciliation_test.go
  tests/integration/testsuites/custom-domain/manifests/testing-app.yaml
  tests/integration/testsuites/istio-jwt/manifests/testing-app.yaml
  tests/integration/testsuites/ory/manifests/testing-app-istio-injection.yaml
  tests/integration/testsuites/ory/manifests/testing-app.yaml
  tests/integration/testsuites/upgrade/manifests/testing-app.yaml
Labels: lgtm, size/L, cla: yes

#1712 Upgrading sec scanner config to 2.11.2
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1714 Upgrading sec scanner config to 2.10.5
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1715 Script for running UI tests locally
  hack/run-ui-tests-locally-k3d.sh
Labels: lgtm, size/M, cla: yes

#1729 fix: update APIRule references in zero-downtime migration test
  tests/integration/scripts/test-zero-downtime.sh
Labels: size/XS, cla: yes

#1731 Fix a broken link in the tutorials README
  docs/user/tutorials/README.md
Labels: lgtm, size/XS, cla: yes

#1722 Fix release workflow adjustment
  .github/workflows/call-integration-release.yaml
  .github/workflows/post-main-integration.yaml
  .github/workflows/pull-request-release.yaml
Labels: lgtm, size/L, cla: yes

#1732 Fix missing checkout ref in changes filter in call-pull-int workflow
  .github/workflows/call-pull-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1730 Add the list of changes in APIRule v2
  docs/user/_sidebar.md
  docs/user/custom-resources/apirule/04-60-apirule-migration.md
  docs/user/custom-resources/apirule/04-70-changes-in-apirule-v2.md
Labels: lgtm, size/M, cla: yes

#1733 Add missing deep clone for upgrade test, fix indentation for one jobs
  .github/workflows/call-integration-release.yaml
  .github/workflows/post-main-integration.yaml
Labels: lgtm, size/M, cla: yes

#1736 Fix the link to APIRule Migration Procedure in the sidebar
  docs/user/_sidebar.md
Labels: size/XS, cla: yes

#1737 Remove redundant ref in upgrade test in call-int-rel
  .github/workflows/call-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1738 Release 3.0.0 security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1739 add RNs for APIRule 3.0.0
  docs/release-notes/3.0.0.md
Labels: lgtm, size/S, cla: yes

#1740 add RNs for APIRule 3.0.0 (#1739)
  docs/release-notes/3.0.0.md
Labels: lgtm, size/S, cla: yes

#1743 Unify pull request workflow among regular and release branches
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/M, cla: yes

#1744 Update sec-scanners-config.yaml for release 3.0.0
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
